CreateHBETextDraws(playerid)
{
    HBE[playerid][0] = CreatePlayerTextDraw(playerid, 149.000000, 367.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HBE[playerid][0], 4);
	PlayerTextDrawLetterSize(playerid, HBE[playerid][0], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBE[playerid][0], 54.000000, 13.000000);
	PlayerTextDrawSetOutline(playerid, HBE[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, HBE[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, HBE[playerid][0], 1);
	PlayerTextDrawColor(playerid, HBE[playerid][0], 673720575);
	PlayerTextDrawBackgroundColor(playerid, HBE[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, HBE[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, HBE[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, HBE[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, HBE[playerid][0], 0);

	HBE[playerid][1] = CreatePlayerTextDraw(playerid, 149.000000, 407.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HBE[playerid][1], 4);
	PlayerTextDrawLetterSize(playerid, HBE[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBE[playerid][1], 54.000000, 13.000000);
	PlayerTextDrawSetOutline(playerid, HBE[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, HBE[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, HBE[playerid][1], 1);
	PlayerTextDrawColor(playerid, HBE[playerid][1], 673720575);
	PlayerTextDrawBackgroundColor(playerid, HBE[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, HBE[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, HBE[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, HBE[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, HBE[playerid][1], 0);

	HBE[playerid][2] = CreatePlayerTextDraw(playerid, 149.000000, 387.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HBE[playerid][2], 4);
	PlayerTextDrawLetterSize(playerid, HBE[playerid][2], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBE[playerid][2], 54.000000, 13.000000);
	PlayerTextDrawSetOutline(playerid, HBE[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, HBE[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, HBE[playerid][2], 1);
	PlayerTextDrawColor(playerid, HBE[playerid][2], 673720575);
	PlayerTextDrawBackgroundColor(playerid, HBE[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, HBE[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, HBE[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, HBE[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, HBE[playerid][2], 0);

	HBE[playerid][3] = CreatePlayerTextDraw(playerid, 149.000000, 367.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HBE[playerid][3], 4);
	PlayerTextDrawLetterSize(playerid, HBE[playerid][3], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBE[playerid][3], 13.000000, 13.000000);
	PlayerTextDrawSetOutline(playerid, HBE[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, HBE[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, HBE[playerid][3], 1);
	PlayerTextDrawColor(playerid, HBE[playerid][3], 553605887);
	PlayerTextDrawBackgroundColor(playerid, HBE[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, HBE[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, HBE[playerid][3], 1);
	PlayerTextDrawSetProportional(playerid, HBE[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, HBE[playerid][3], 0);

	HBE[playerid][4] = CreatePlayerTextDraw(playerid, 149.000000, 387.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HBE[playerid][4], 4);
	PlayerTextDrawLetterSize(playerid, HBE[playerid][4], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBE[playerid][4], 13.000000, 13.000000);
	PlayerTextDrawSetOutline(playerid, HBE[playerid][4], 1);
	PlayerTextDrawSetShadow(playerid, HBE[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, HBE[playerid][4], 1);
	PlayerTextDrawColor(playerid, HBE[playerid][4], 598405631);
	PlayerTextDrawBackgroundColor(playerid, HBE[playerid][4], 255);
	PlayerTextDrawBoxColor(playerid, HBE[playerid][4], 50);
	PlayerTextDrawUseBox(playerid, HBE[playerid][4], 1);
	PlayerTextDrawSetProportional(playerid, HBE[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, HBE[playerid][4], 0);

	HBE[playerid][5] = CreatePlayerTextDraw(playerid, 149.000000, 407.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HBE[playerid][5], 4);
	PlayerTextDrawLetterSize(playerid, HBE[playerid][5], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBE[playerid][5], 13.000000, 13.000000);
	PlayerTextDrawSetOutline(playerid, HBE[playerid][5], 1);
	PlayerTextDrawSetShadow(playerid, HBE[playerid][5], 0);
	PlayerTextDrawAlignment(playerid, HBE[playerid][5], 1);
	PlayerTextDrawColor(playerid, HBE[playerid][5], -16777066);
	PlayerTextDrawBackgroundColor(playerid, HBE[playerid][5], 255);
	PlayerTextDrawBoxColor(playerid, HBE[playerid][5], 50);
	PlayerTextDrawUseBox(playerid, HBE[playerid][5], 1);
	PlayerTextDrawSetProportional(playerid, HBE[playerid][5], 1);
	PlayerTextDrawSetSelectable(playerid, HBE[playerid][5], 0);

	HBEProgressHunger[playerid] = CreatePlayerTextDraw(playerid, 162.000000, 367.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HBEProgressHunger[playerid], 4);
	PlayerTextDrawLetterSize(playerid, HBEProgressHunger[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBEProgressHunger[playerid], 41.000000, 13.000000);
	PlayerTextDrawSetOutline(playerid, HBEProgressHunger[playerid], 1);
	PlayerTextDrawSetShadow(playerid, HBEProgressHunger[playerid], 0);
	PlayerTextDrawAlignment(playerid, HBEProgressHunger[playerid], 1);
	PlayerTextDrawColor(playerid, HBEProgressHunger[playerid], 549870250);
	PlayerTextDrawBackgroundColor(playerid, HBEProgressHunger[playerid], 255);
	PlayerTextDrawBoxColor(playerid, HBEProgressHunger[playerid], 50);
	PlayerTextDrawUseBox(playerid, HBEProgressHunger[playerid], 1);
	PlayerTextDrawSetProportional(playerid, HBEProgressHunger[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, HBEProgressHunger[playerid], 0);

	HBEProgressThirst[playerid] = CreatePlayerTextDraw(playerid, 162.000000, 387.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HBEProgressThirst[playerid], 4);
	PlayerTextDrawLetterSize(playerid, HBEProgressThirst[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBEProgressThirst[playerid], 41.000000, 13.000000);
	PlayerTextDrawSetOutline(playerid, HBEProgressThirst[playerid], 1);
	PlayerTextDrawSetShadow(playerid, HBEProgressThirst[playerid], 0);
	PlayerTextDrawAlignment(playerid, HBEProgressThirst[playerid], 1);
	PlayerTextDrawColor(playerid, HBEProgressThirst[playerid], 1521088170);
	PlayerTextDrawBackgroundColor(playerid, HBEProgressThirst[playerid], 255);
	PlayerTextDrawBoxColor(playerid, HBEProgressThirst[playerid], 50);
	PlayerTextDrawUseBox(playerid, HBEProgressThirst[playerid], 1);
	PlayerTextDrawSetProportional(playerid, HBEProgressThirst[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, HBEProgressThirst[playerid], 0);

	HBEProgressStress[playerid] = CreatePlayerTextDraw(playerid, 162.000000, 407.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HBEProgressStress[playerid], 4);
	PlayerTextDrawLetterSize(playerid, HBEProgressStress[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBEProgressStress[playerid], 41.000000, 13.000000);
	PlayerTextDrawSetOutline(playerid, HBEProgressStress[playerid], 1);
	PlayerTextDrawSetShadow(playerid, HBEProgressStress[playerid], 0);
	PlayerTextDrawAlignment(playerid, HBEProgressStress[playerid], 1);
	PlayerTextDrawColor(playerid, HBEProgressStress[playerid], -1105388118);
	PlayerTextDrawBackgroundColor(playerid, HBEProgressStress[playerid], 255);
	PlayerTextDrawBoxColor(playerid, HBEProgressStress[playerid], 50);
	PlayerTextDrawUseBox(playerid, HBEProgressStress[playerid], 1);
	PlayerTextDrawSetProportional(playerid, HBEProgressStress[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, HBEProgressStress[playerid], 0);

	HBEIconHunger[playerid][0] = CreatePlayerTextDraw(playerid, 148.000000, 366.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, HBEIconHunger[playerid][0], 4);
	PlayerTextDrawLetterSize(playerid, HBEIconHunger[playerid][0], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBEIconHunger[playerid][0], 15.000000, 15.000000);
	PlayerTextDrawSetOutline(playerid, HBEIconHunger[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, HBEIconHunger[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, HBEIconHunger[playerid][0], 1);
	PlayerTextDrawColor(playerid, HBEIconHunger[playerid][0], -3841);
	PlayerTextDrawBackgroundColor(playerid, HBEIconHunger[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, HBEIconHunger[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, HBEIconHunger[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, HBEIconHunger[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, HBEIconHunger[playerid][0], 0);

	HBEIconHunger[playerid][1] = CreatePlayerTextDraw(playerid, 150.000000, 373.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HBEIconHunger[playerid][1], 4);
	PlayerTextDrawLetterSize(playerid, HBEIconHunger[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBEIconHunger[playerid][1], 10.500000, 6.000000);
	PlayerTextDrawSetOutline(playerid, HBEIconHunger[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, HBEIconHunger[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, HBEIconHunger[playerid][1], 1);
	PlayerTextDrawColor(playerid, HBEIconHunger[playerid][1], 553605887);
	PlayerTextDrawBackgroundColor(playerid, HBEIconHunger[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, HBEIconHunger[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, HBEIconHunger[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, HBEIconHunger[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, HBEIconHunger[playerid][1], 0);

	HBEIconHunger[playerid][2] = CreatePlayerTextDraw(playerid, 150.699996, 374.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HBEIconHunger[playerid][2], 4);
	PlayerTextDrawLetterSize(playerid, HBEIconHunger[playerid][2], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBEIconHunger[playerid][2], 9.500000, 1.000000);
	PlayerTextDrawSetOutline(playerid, HBEIconHunger[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, HBEIconHunger[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, HBEIconHunger[playerid][2], 1);
	PlayerTextDrawColor(playerid, HBEIconHunger[playerid][2], -3841);
	PlayerTextDrawBackgroundColor(playerid, HBEIconHunger[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, HBEIconHunger[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, HBEIconHunger[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, HBEIconHunger[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, HBEIconHunger[playerid][2], 0);

	HBEIconHunger[playerid][3] = CreatePlayerTextDraw(playerid, 150.699996, 376.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HBEIconHunger[playerid][3], 4);
	PlayerTextDrawLetterSize(playerid, HBEIconHunger[playerid][3], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBEIconHunger[playerid][3], 9.500000, 2.000000);
	PlayerTextDrawSetOutline(playerid, HBEIconHunger[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, HBEIconHunger[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, HBEIconHunger[playerid][3], 1);
	PlayerTextDrawColor(playerid, HBEIconHunger[playerid][3], -3841);
	PlayerTextDrawBackgroundColor(playerid, HBEIconHunger[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, HBEIconHunger[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, HBEIconHunger[playerid][3], 1);
	PlayerTextDrawSetProportional(playerid, HBEIconHunger[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, HBEIconHunger[playerid][3], 0);

	HBEIconThirst[playerid][0] = CreatePlayerTextDraw(playerid, 151.500000, 388.500000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, HBEIconThirst[playerid][0], 4);
	PlayerTextDrawLetterSize(playerid, HBEIconThirst[playerid][0], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBEIconThirst[playerid][0], 7.500000, 11.500000);
	PlayerTextDrawSetOutline(playerid, HBEIconThirst[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, HBEIconThirst[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, HBEIconThirst[playerid][0], 1);
	PlayerTextDrawColor(playerid, HBEIconThirst[playerid][0], -3841);
	PlayerTextDrawBackgroundColor(playerid, HBEIconThirst[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, HBEIconThirst[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, HBEIconThirst[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, HBEIconThirst[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, HBEIconThirst[playerid][0], 0);

	HBEIconThirst[playerid][1] = CreatePlayerTextDraw(playerid, 154.250000, 389.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HBEIconThirst[playerid][1], 4);
	PlayerTextDrawLetterSize(playerid, HBEIconThirst[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBEIconThirst[playerid][1], 2.000000, 2.500000);
	PlayerTextDrawSetOutline(playerid, HBEIconThirst[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, HBEIconThirst[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, HBEIconThirst[playerid][1], 1);
	PlayerTextDrawColor(playerid, HBEIconThirst[playerid][1], -3841);
	PlayerTextDrawBackgroundColor(playerid, HBEIconThirst[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, HBEIconThirst[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, HBEIconThirst[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, HBEIconThirst[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, HBEIconThirst[playerid][1], 0);

	HBEIconThirst[playerid][2] = CreatePlayerTextDraw(playerid, 156.250000, 393.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HBEIconThirst[playerid][2], 4);
	PlayerTextDrawLetterSize(playerid, HBEIconThirst[playerid][2], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBEIconThirst[playerid][2], 2.500000, 1.000000);
	PlayerTextDrawSetOutline(playerid, HBEIconThirst[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, HBEIconThirst[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, HBEIconThirst[playerid][2], 1);
	PlayerTextDrawColor(playerid, HBEIconThirst[playerid][2], 598405631);
	PlayerTextDrawBackgroundColor(playerid, HBEIconThirst[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, HBEIconThirst[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, HBEIconThirst[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, HBEIconThirst[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, HBEIconThirst[playerid][2], 0);

	HBEIconThirst[playerid][3] = CreatePlayerTextDraw(playerid, 156.250000, 395.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HBEIconThirst[playerid][3], 4);
	PlayerTextDrawLetterSize(playerid, HBEIconThirst[playerid][3], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBEIconThirst[playerid][3], 2.500000, 1.000000);
	PlayerTextDrawSetOutline(playerid, HBEIconThirst[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, HBEIconThirst[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, HBEIconThirst[playerid][3], 1);
	PlayerTextDrawColor(playerid, HBEIconThirst[playerid][3], 598405631);
	PlayerTextDrawBackgroundColor(playerid, HBEIconThirst[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, HBEIconThirst[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, HBEIconThirst[playerid][3], 1);
	PlayerTextDrawSetProportional(playerid, HBEIconThirst[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, HBEIconThirst[playerid][3], 0);

	HBEIconStress[playerid][0] = CreatePlayerTextDraw(playerid, 150.500000, 408.500000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, HBEIconStress[playerid][0], 4);
	PlayerTextDrawLetterSize(playerid, HBEIconStress[playerid][0], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBEIconStress[playerid][0], 4.500000, 10.500000);
	PlayerTextDrawSetOutline(playerid, HBEIconStress[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, HBEIconStress[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, HBEIconStress[playerid][0], 1);
	PlayerTextDrawColor(playerid, HBEIconStress[playerid][0], -3841);
	PlayerTextDrawBackgroundColor(playerid, HBEIconStress[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, HBEIconStress[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, HBEIconStress[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, HBEIconStress[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, HBEIconStress[playerid][0], 0);

	HBEIconStress[playerid][1] = CreatePlayerTextDraw(playerid, 155.500000, 408.500000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, HBEIconStress[playerid][1], 4);
	PlayerTextDrawLetterSize(playerid, HBEIconStress[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBEIconStress[playerid][1], 4.500000, 10.500000);
	PlayerTextDrawSetOutline(playerid, HBEIconStress[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, HBEIconStress[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, HBEIconStress[playerid][1], 1);
	PlayerTextDrawColor(playerid, HBEIconStress[playerid][1], -3841);
	PlayerTextDrawBackgroundColor(playerid, HBEIconStress[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, HBEIconStress[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, HBEIconStress[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, HBEIconStress[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, HBEIconStress[playerid][1], 0);

	HBEIconStress[playerid][2] = CreatePlayerTextDraw(playerid, 153.250000, 412.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HBEIconStress[playerid][2], 4);
	PlayerTextDrawLetterSize(playerid, HBEIconStress[playerid][2], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBEIconStress[playerid][2], 4.000000, 1.000000);
	PlayerTextDrawSetOutline(playerid, HBEIconStress[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, HBEIconStress[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, HBEIconStress[playerid][2], 1);
	PlayerTextDrawColor(playerid, HBEIconStress[playerid][2], -16777066);
	PlayerTextDrawBackgroundColor(playerid, HBEIconStress[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, HBEIconStress[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, HBEIconStress[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, HBEIconStress[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, HBEIconStress[playerid][2], 0);

	HBEIconStress[playerid][3] = CreatePlayerTextDraw(playerid, 153.250000, 414.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HBEIconStress[playerid][3], 4);
	PlayerTextDrawLetterSize(playerid, HBEIconStress[playerid][3], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBEIconStress[playerid][3], 4.000000, 1.000000);
	PlayerTextDrawSetOutline(playerid, HBEIconStress[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, HBEIconStress[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, HBEIconStress[playerid][3], 1);
	PlayerTextDrawColor(playerid, HBEIconStress[playerid][3], -16777066);
	PlayerTextDrawBackgroundColor(playerid, HBEIconStress[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, HBEIconStress[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, HBEIconStress[playerid][3], 1);
	PlayerTextDrawSetProportional(playerid, HBEIconStress[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, HBEIconStress[playerid][3], 0);
}