CreateSpeedoTextDraws(playerid)
{
    Speedo[playerid][0] = CreatePlayerTextDraw(playerid, 166.250000, 327.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, Speedo[playerid][0], 4);
	PlayerTextDrawLetterSize(playerid, Speedo[playerid][0], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, Speedo[playerid][0], 77.000000, 26.500000);
	PlayerTextDrawSetOutline(playerid, Speedo[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, Speedo[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, Speedo[playerid][0], 1);
	PlayerTextDrawColor(playerid, Speedo[playerid][0], -1210123777);
	PlayerTextDrawBackgroundColor(playerid, Speedo[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, Speedo[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, Speedo[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, Speedo[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, Speedo[playerid][0], 0);

	Speedo[playerid][1] = CreatePlayerTextDraw(playerid, 172.250000, 329.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, Speedo[playerid][1], 4);
	PlayerTextDrawLetterSize(playerid, Speedo[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, Speedo[playerid][1], 69.500000, 22.500000);
	PlayerTextDrawSetOutline(playerid, Speedo[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, Speedo[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, Speedo[playerid][1], 1);
	PlayerTextDrawColor(playerid, Speedo[playerid][1], 673720575);
	PlayerTextDrawBackgroundColor(playerid, Speedo[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, Speedo[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, Speedo[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, Speedo[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, Speedo[playerid][1], 0);

	Speedo[playerid][2] = CreatePlayerTextDraw(playerid, 137.500000, 315.500000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, Speedo[playerid][2], 4);
	PlayerTextDrawLetterSize(playerid, Speedo[playerid][2], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, Speedo[playerid][2], 50.000000, 50.000000);
	PlayerTextDrawSetOutline(playerid, Speedo[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, Speedo[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, Speedo[playerid][2], 1);
	PlayerTextDrawColor(playerid, Speedo[playerid][2], 673720575);
	PlayerTextDrawBackgroundColor(playerid, Speedo[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, Speedo[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, Speedo[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, Speedo[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, Speedo[playerid][2], 0);

	SpeedoSpeedText[playerid] = CreatePlayerTextDraw(playerid, 163.000000, 330.000000, "0");
	PlayerTextDrawFont(playerid, SpeedoSpeedText[playerid], 3);
	PlayerTextDrawLetterSize(playerid, SpeedoSpeedText[playerid], 0.333332, 1.399999);
	PlayerTextDrawTextSize(playerid, SpeedoSpeedText[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, SpeedoSpeedText[playerid], 0);
	PlayerTextDrawSetShadow(playerid, SpeedoSpeedText[playerid], 0);
	PlayerTextDrawAlignment(playerid, SpeedoSpeedText[playerid], 2);
	PlayerTextDrawColor(playerid, SpeedoSpeedText[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, SpeedoSpeedText[playerid], 255);
	PlayerTextDrawBoxColor(playerid, SpeedoSpeedText[playerid], 50);
	PlayerTextDrawUseBox(playerid, SpeedoSpeedText[playerid], 0);
	PlayerTextDrawSetProportional(playerid, SpeedoSpeedText[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, SpeedoSpeedText[playerid], 0);

	Speedo[playerid][3] = CreatePlayerTextDraw(playerid, 163.000000, 345.000000, "KMH");
	PlayerTextDrawFont(playerid, Speedo[playerid][3], 3);
	PlayerTextDrawLetterSize(playerid, Speedo[playerid][3], 0.150000, 0.500000);
	PlayerTextDrawTextSize(playerid, Speedo[playerid][3], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, Speedo[playerid][3], 0);
	PlayerTextDrawSetShadow(playerid, Speedo[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, Speedo[playerid][3], 2);
	PlayerTextDrawColor(playerid, Speedo[playerid][3], -1);
	PlayerTextDrawBackgroundColor(playerid, Speedo[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, Speedo[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, Speedo[playerid][3], 0);
	PlayerTextDrawSetProportional(playerid, Speedo[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, Speedo[playerid][3], 0);

	Speedo[playerid][4] = CreatePlayerTextDraw(playerid, 179.000000, 333.000000, "HP");
	PlayerTextDrawFont(playerid, Speedo[playerid][4], 1);
	PlayerTextDrawLetterSize(playerid, Speedo[playerid][4], 0.170833, 0.800000);
	PlayerTextDrawTextSize(playerid, Speedo[playerid][4], 400.000000, 113.000000);
	PlayerTextDrawSetOutline(playerid, Speedo[playerid][4], 0);
	PlayerTextDrawSetShadow(playerid, Speedo[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, Speedo[playerid][4], 1);
	PlayerTextDrawColor(playerid, Speedo[playerid][4], -1);
	PlayerTextDrawBackgroundColor(playerid, Speedo[playerid][4], 255);
	PlayerTextDrawBoxColor(playerid, Speedo[playerid][4], 50);
	PlayerTextDrawUseBox(playerid, Speedo[playerid][4], 0);
	PlayerTextDrawSetProportional(playerid, Speedo[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, Speedo[playerid][4], 0);

	Speedo[playerid][5] = CreatePlayerTextDraw(playerid, 179.000000, 341.000000, "F");
	PlayerTextDrawFont(playerid, Speedo[playerid][5], 1);
	PlayerTextDrawLetterSize(playerid, Speedo[playerid][5], 0.170833, 0.800000);
	PlayerTextDrawTextSize(playerid, Speedo[playerid][5], 400.000000, 113.000000);
	PlayerTextDrawSetOutline(playerid, Speedo[playerid][5], 0);
	PlayerTextDrawSetShadow(playerid, Speedo[playerid][5], 0);
	PlayerTextDrawAlignment(playerid, Speedo[playerid][5], 1);
	PlayerTextDrawColor(playerid, Speedo[playerid][5], -1);
	PlayerTextDrawBackgroundColor(playerid, Speedo[playerid][5], 255);
	PlayerTextDrawBoxColor(playerid, Speedo[playerid][5], 50);
	PlayerTextDrawUseBox(playerid, Speedo[playerid][5], 0);
	PlayerTextDrawSetProportional(playerid, Speedo[playerid][5], 1);
	PlayerTextDrawSetSelectable(playerid, Speedo[playerid][5], 0);

	SpeedoHPText[playerid] = CreatePlayerTextDraw(playerid, 190.250000, 333.500000, "100%");
	PlayerTextDrawFont(playerid, SpeedoHPText[playerid], 1);
	PlayerTextDrawLetterSize(playerid, SpeedoHPText[playerid], 0.179166, 0.699998);
	PlayerTextDrawTextSize(playerid, SpeedoHPText[playerid], 382.000000, 10.000000);
	PlayerTextDrawSetOutline(playerid, SpeedoHPText[playerid], 0);
	PlayerTextDrawSetShadow(playerid, SpeedoHPText[playerid], 0);
	PlayerTextDrawAlignment(playerid, SpeedoHPText[playerid], 1);
	PlayerTextDrawColor(playerid, SpeedoHPText[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, SpeedoHPText[playerid], 255);
	PlayerTextDrawBoxColor(playerid, SpeedoHPText[playerid], 50);
	PlayerTextDrawUseBox(playerid, SpeedoHPText[playerid], 0);
	PlayerTextDrawSetProportional(playerid, SpeedoHPText[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, SpeedoHPText[playerid], 0);

	SpeedoFuelText[playerid] = CreatePlayerTextDraw(playerid, 190.250000, 341.500000, "100%");
	PlayerTextDrawFont(playerid, SpeedoFuelText[playerid], 1);
	PlayerTextDrawLetterSize(playerid, SpeedoFuelText[playerid], 0.179166, 0.699998);
	PlayerTextDrawTextSize(playerid, SpeedoFuelText[playerid], 382.000000, 10.000000);
	PlayerTextDrawSetOutline(playerid, SpeedoFuelText[playerid], 0);
	PlayerTextDrawSetShadow(playerid, SpeedoFuelText[playerid], 0);
	PlayerTextDrawAlignment(playerid, SpeedoFuelText[playerid], 1);
	PlayerTextDrawColor(playerid, SpeedoFuelText[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, SpeedoFuelText[playerid], 255);
	PlayerTextDrawBoxColor(playerid, SpeedoFuelText[playerid], 50);
	PlayerTextDrawUseBox(playerid, SpeedoFuelText[playerid], 0);
	PlayerTextDrawSetProportional(playerid, SpeedoFuelText[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, SpeedoFuelText[playerid], 0);

	SpeedoCompassText[playerid] = CreatePlayerTextDraw(playerid, 229.000000, 333.000000, "N");
	PlayerTextDrawFont(playerid, SpeedoCompassText[playerid], 1);
	PlayerTextDrawLetterSize(playerid, SpeedoCompassText[playerid], 0.349999, 1.450000);
	PlayerTextDrawTextSize(playerid, SpeedoCompassText[playerid], 400.000000, 113.000000);
	PlayerTextDrawSetOutline(playerid, SpeedoCompassText[playerid], 0);
	PlayerTextDrawSetShadow(playerid, SpeedoCompassText[playerid], 0);
	PlayerTextDrawAlignment(playerid, SpeedoCompassText[playerid], 2);
	PlayerTextDrawColor(playerid, SpeedoCompassText[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, SpeedoCompassText[playerid], 255);
	PlayerTextDrawBoxColor(playerid, SpeedoCompassText[playerid], 50);
	PlayerTextDrawUseBox(playerid, SpeedoCompassText[playerid], 0);
	PlayerTextDrawSetProportional(playerid, SpeedoCompassText[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, SpeedoCompassText[playerid], 0);

	Speedo[playerid][6] = CreatePlayerTextDraw(playerid, 216.250000, 329.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, Speedo[playerid][6], 4);
	PlayerTextDrawLetterSize(playerid, Speedo[playerid][6], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, Speedo[playerid][6], 0.500000, 22.500000);
	PlayerTextDrawSetOutline(playerid, Speedo[playerid][6], 1);
	PlayerTextDrawSetShadow(playerid, Speedo[playerid][6], 0);
	PlayerTextDrawAlignment(playerid, Speedo[playerid][6], 1);
	PlayerTextDrawColor(playerid, Speedo[playerid][6], -1210123777);
	PlayerTextDrawBackgroundColor(playerid, Speedo[playerid][6], 255);
	PlayerTextDrawBoxColor(playerid, Speedo[playerid][6], 50);
	PlayerTextDrawUseBox(playerid, Speedo[playerid][6], 1);
	PlayerTextDrawSetProportional(playerid, Speedo[playerid][6], 1);
	PlayerTextDrawSetSelectable(playerid, Speedo[playerid][6], 0);

	SpeedoModelText[playerid] = CreatePlayerTextDraw(playerid, 171.000000, 318.000000, "Hotring Racer A");
	PlayerTextDrawFont(playerid, SpeedoModelText[playerid], 1);
	PlayerTextDrawLetterSize(playerid, SpeedoModelText[playerid], 0.150000, 0.800000);
	PlayerTextDrawTextSize(playerid, SpeedoModelText[playerid], 400.000000, 113.000000);
	PlayerTextDrawSetOutline(playerid, SpeedoModelText[playerid], 0);
	PlayerTextDrawSetShadow(playerid, SpeedoModelText[playerid], 0);
	PlayerTextDrawAlignment(playerid, SpeedoModelText[playerid], 1);
	PlayerTextDrawColor(playerid, SpeedoModelText[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, SpeedoModelText[playerid], 255);
	PlayerTextDrawBoxColor(playerid, SpeedoModelText[playerid], 50);
	PlayerTextDrawUseBox(playerid, SpeedoModelText[playerid], 0);
	PlayerTextDrawSetProportional(playerid, SpeedoModelText[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, SpeedoModelText[playerid], 0);
}