CreateLoginTextDraws(playerid)
{
    LoginTD[playerid][0] = CreatePlayerTextDraw(playerid, 313.000000, 189.500000, "_");
	PlayerTextDrawFont(playerid, LoginTD[playerid][0], 1);
	PlayerTextDrawLetterSize(playerid, LoginTD[playerid][0], 0.049998, 6.449995);
	PlayerTextDrawTextSize(playerid, LoginTD[playerid][0], 334.500000, 129.500000);
	PlayerTextDrawSetOutline(playerid, LoginTD[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, LoginTD[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, LoginTD[playerid][0], 2);
	PlayerTextDrawColor(playerid, LoginTD[playerid][0], -1);
	PlayerTextDrawBackgroundColor(playerid, LoginTD[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, LoginTD[playerid][0], 1906762751);
	PlayerTextDrawUseBox(playerid, LoginTD[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, LoginTD[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, LoginTD[playerid][0], 0);

	LoginTD[playerid][1] = CreatePlayerTextDraw(playerid, 313.000000, 190.000000, "_");
	PlayerTextDrawFont(playerid, LoginTD[playerid][1], 1);
	PlayerTextDrawLetterSize(playerid, LoginTD[playerid][1], 0.041666, 6.249997);
	PlayerTextDrawTextSize(playerid, LoginTD[playerid][1], 334.500000, 128.000000);
	PlayerTextDrawSetOutline(playerid, LoginTD[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, LoginTD[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, LoginTD[playerid][1], 2);
	PlayerTextDrawColor(playerid, LoginTD[playerid][1], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, LoginTD[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, LoginTD[playerid][1], 673720575);
	PlayerTextDrawUseBox(playerid, LoginTD[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, LoginTD[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, LoginTD[playerid][1], 0);

	LoginTD[playerid][2] = CreatePlayerTextDraw(playerid, 255.000000, 197.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, LoginTD[playerid][2], 4);
	PlayerTextDrawLetterSize(playerid, LoginTD[playerid][2], 0.250000, 1.699998);
	PlayerTextDrawTextSize(playerid, LoginTD[playerid][2], 116.500000, 16.500000);
	PlayerTextDrawSetOutline(playerid, LoginTD[playerid][2], 0);
	PlayerTextDrawSetShadow(playerid, LoginTD[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, LoginTD[playerid][2], 2);
	PlayerTextDrawColor(playerid, LoginTD[playerid][2], 1872944383);
	PlayerTextDrawBackgroundColor(playerid, LoginTD[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, LoginTD[playerid][2], 1906762751);
	PlayerTextDrawUseBox(playerid, LoginTD[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, LoginTD[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, LoginTD[playerid][2], 0);

	LoginCharButton[playerid] = CreatePlayerTextDraw(playerid, 255.000000, 222.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, LoginCharButton[playerid], 4);
	PlayerTextDrawLetterSize(playerid, LoginCharButton[playerid], 0.250000, 1.699998);
	PlayerTextDrawTextSize(playerid, LoginCharButton[playerid], 116.500000, 16.500000);
	PlayerTextDrawSetOutline(playerid, LoginCharButton[playerid], 0);
	PlayerTextDrawSetShadow(playerid, LoginCharButton[playerid], 0);
	PlayerTextDrawAlignment(playerid, LoginCharButton[playerid], 2);
	PlayerTextDrawColor(playerid, LoginCharButton[playerid], 1872944383);
	PlayerTextDrawBackgroundColor(playerid, LoginCharButton[playerid], 255);
	PlayerTextDrawBoxColor(playerid, LoginCharButton[playerid], 1906762751);
	PlayerTextDrawUseBox(playerid, LoginCharButton[playerid], 1);
	PlayerTextDrawSetProportional(playerid, LoginCharButton[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, LoginCharButton[playerid], 1);

	LoginTD[playerid][3] = CreatePlayerTextDraw(playerid, 313.000000, 179.000000, "Fountain Daily");
	PlayerTextDrawFont(playerid, LoginTD[playerid][3], 0);
	PlayerTextDrawLetterSize(playerid, LoginTD[playerid][3], 0.341666, 1.250000);
	PlayerTextDrawTextSize(playerid, LoginTD[playerid][3], 400.000000, 232.000000);
	PlayerTextDrawSetOutline(playerid, LoginTD[playerid][3], 0);
	PlayerTextDrawSetShadow(playerid, LoginTD[playerid][3], 1);
	PlayerTextDrawAlignment(playerid, LoginTD[playerid][3], 2);
	PlayerTextDrawColor(playerid, LoginTD[playerid][3], -1);
	PlayerTextDrawBackgroundColor(playerid, LoginTD[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, LoginTD[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, LoginTD[playerid][3], 0);
	PlayerTextDrawSetProportional(playerid, LoginTD[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, LoginTD[playerid][3], 0);

	LoginTD[playerid][4] = CreatePlayerTextDraw(playerid, 258.000000, 197.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, LoginTD[playerid][4], 4);
	PlayerTextDrawLetterSize(playerid, LoginTD[playerid][4], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, LoginTD[playerid][4], 10.000000, 10.000000);
	PlayerTextDrawSetOutline(playerid, LoginTD[playerid][4], 1);
	PlayerTextDrawSetShadow(playerid, LoginTD[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, LoginTD[playerid][4], 1);
	PlayerTextDrawColor(playerid, LoginTD[playerid][4], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, LoginTD[playerid][4], 255);
	PlayerTextDrawBoxColor(playerid, LoginTD[playerid][4], 50);
	PlayerTextDrawUseBox(playerid, LoginTD[playerid][4], 1);
	PlayerTextDrawSetProportional(playerid, LoginTD[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, LoginTD[playerid][4], 0);

	LoginTD[playerid][5] = CreatePlayerTextDraw(playerid, 255.500000, 204.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, LoginTD[playerid][5], 4);
	PlayerTextDrawLetterSize(playerid, LoginTD[playerid][5], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, LoginTD[playerid][5], 15.000000, 10.000000);
	PlayerTextDrawSetOutline(playerid, LoginTD[playerid][5], 1);
	PlayerTextDrawSetShadow(playerid, LoginTD[playerid][5], 0);
	PlayerTextDrawAlignment(playerid, LoginTD[playerid][5], 1);
	PlayerTextDrawColor(playerid, LoginTD[playerid][5], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, LoginTD[playerid][5], 255);
	PlayerTextDrawBoxColor(playerid, LoginTD[playerid][5], 50);
	PlayerTextDrawUseBox(playerid, LoginTD[playerid][5], 1);
	PlayerTextDrawSetProportional(playerid, LoginTD[playerid][5], 1);
	PlayerTextDrawSetSelectable(playerid, LoginTD[playerid][5], 0);

	LoginTD[playerid][6] = CreatePlayerTextDraw(playerid, 258.000000, 222.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, LoginTD[playerid][6], 4);
	PlayerTextDrawLetterSize(playerid, LoginTD[playerid][6], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, LoginTD[playerid][6], 10.000000, 10.000000);
	PlayerTextDrawSetOutline(playerid, LoginTD[playerid][6], 1);
	PlayerTextDrawSetShadow(playerid, LoginTD[playerid][6], 0);
	PlayerTextDrawAlignment(playerid, LoginTD[playerid][6], 1);
	PlayerTextDrawColor(playerid, LoginTD[playerid][6], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, LoginTD[playerid][6], 255);
	PlayerTextDrawBoxColor(playerid, LoginTD[playerid][6], 50);
	PlayerTextDrawUseBox(playerid, LoginTD[playerid][6], 1);
	PlayerTextDrawSetProportional(playerid, LoginTD[playerid][6], 1);
	PlayerTextDrawSetSelectable(playerid, LoginTD[playerid][6], 0);

	LoginTD[playerid][7] = CreatePlayerTextDraw(playerid, 255.500000, 229.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, LoginTD[playerid][7], 4);
	PlayerTextDrawLetterSize(playerid, LoginTD[playerid][7], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, LoginTD[playerid][7], 15.000000, 10.000000);
	PlayerTextDrawSetOutline(playerid, LoginTD[playerid][7], 1);
	PlayerTextDrawSetShadow(playerid, LoginTD[playerid][7], 0);
	PlayerTextDrawAlignment(playerid, LoginTD[playerid][7], 1);
	PlayerTextDrawColor(playerid, LoginTD[playerid][7], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, LoginTD[playerid][7], 255);
	PlayerTextDrawBoxColor(playerid, LoginTD[playerid][7], 50);
	PlayerTextDrawUseBox(playerid, LoginTD[playerid][7], 1);
	PlayerTextDrawSetProportional(playerid, LoginTD[playerid][7], 1);
	PlayerTextDrawSetSelectable(playerid, LoginTD[playerid][7], 0);

	LoginTD[playerid][8] = CreatePlayerTextDraw(playerid, 259.500000, 228.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, LoginTD[playerid][8], 4);
	PlayerTextDrawLetterSize(playerid, LoginTD[playerid][8], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, LoginTD[playerid][8], 15.000000, 10.000000);
	PlayerTextDrawSetOutline(playerid, LoginTD[playerid][8], 1);
	PlayerTextDrawSetShadow(playerid, LoginTD[playerid][8], 0);
	PlayerTextDrawAlignment(playerid, LoginTD[playerid][8], 1);
	PlayerTextDrawColor(playerid, LoginTD[playerid][8], -1061109629);
	PlayerTextDrawBackgroundColor(playerid, LoginTD[playerid][8], 255);
	PlayerTextDrawBoxColor(playerid, LoginTD[playerid][8], 50);
	PlayerTextDrawUseBox(playerid, LoginTD[playerid][8], 1);
	PlayerTextDrawSetProportional(playerid, LoginTD[playerid][8], 1);
	PlayerTextDrawSetSelectable(playerid, LoginTD[playerid][8], 0);

	LoginTD[playerid][9] = CreatePlayerTextDraw(playerid, 262.000000, 221.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, LoginTD[playerid][9], 4);
	PlayerTextDrawLetterSize(playerid, LoginTD[playerid][9], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, LoginTD[playerid][9], 10.000000, 10.000000);
	PlayerTextDrawSetOutline(playerid, LoginTD[playerid][9], 1);
	PlayerTextDrawSetShadow(playerid, LoginTD[playerid][9], 0);
	PlayerTextDrawAlignment(playerid, LoginTD[playerid][9], 1);
	PlayerTextDrawColor(playerid, LoginTD[playerid][9], -1061109630);
	PlayerTextDrawBackgroundColor(playerid, LoginTD[playerid][9], 255);
	PlayerTextDrawBoxColor(playerid, LoginTD[playerid][9], 50);
	PlayerTextDrawUseBox(playerid, LoginTD[playerid][9], 1);
	PlayerTextDrawSetProportional(playerid, LoginTD[playerid][9], 1);
	PlayerTextDrawSetSelectable(playerid, LoginTD[playerid][9], 0);

	LoginMainButton[playerid] = CreatePlayerTextDraw(playerid, 336.000000, 251.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, LoginMainButton[playerid], 4);
	PlayerTextDrawLetterSize(playerid, LoginMainButton[playerid], 0.041666, 1.549998);
	PlayerTextDrawTextSize(playerid, LoginMainButton[playerid], 43.300003, 12.500000);
	PlayerTextDrawSetOutline(playerid, LoginMainButton[playerid], 1);
	PlayerTextDrawSetShadow(playerid, LoginMainButton[playerid], 0);
	PlayerTextDrawAlignment(playerid, LoginMainButton[playerid], 2);
	PlayerTextDrawColor(playerid, LoginMainButton[playerid], 1889854207);
	PlayerTextDrawBackgroundColor(playerid, LoginMainButton[playerid], 255);
	PlayerTextDrawBoxColor(playerid, LoginMainButton[playerid], -1);
	PlayerTextDrawUseBox(playerid, LoginMainButton[playerid], 0);
	PlayerTextDrawSetProportional(playerid, LoginMainButton[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, LoginMainButton[playerid], 1);

	LoginTD[playerid][10] = CreatePlayerTextDraw(playerid, 357.500000, 252.000000, "Login");
	PlayerTextDrawFont(playerid, LoginTD[playerid][10], 2);
	PlayerTextDrawLetterSize(playerid, LoginTD[playerid][10], 0.200000, 1.100000);
	PlayerTextDrawTextSize(playerid, LoginTD[playerid][10], 400.000000, 116.500000);
	PlayerTextDrawSetOutline(playerid, LoginTD[playerid][10], 0);
	PlayerTextDrawSetShadow(playerid, LoginTD[playerid][10], 0);
	PlayerTextDrawAlignment(playerid, LoginTD[playerid][10], 2);
	PlayerTextDrawColor(playerid, LoginTD[playerid][10], -1);
	PlayerTextDrawBackgroundColor(playerid, LoginTD[playerid][10], 255);
	PlayerTextDrawBoxColor(playerid, LoginTD[playerid][10], 50);
	PlayerTextDrawUseBox(playerid, LoginTD[playerid][10], 0);
	PlayerTextDrawSetProportional(playerid, LoginTD[playerid][10], 1);
	PlayerTextDrawSetSelectable(playerid, LoginTD[playerid][10], 0);

	LoginCharacter[playerid] = CreatePlayerTextDraw(playerid, 320.500000, 225.000000, "Select Character");
	PlayerTextDrawFont(playerid, LoginCharacter[playerid], 2);
	PlayerTextDrawLetterSize(playerid, LoginCharacter[playerid], 0.200000, 1.100000);
	PlayerTextDrawTextSize(playerid, LoginCharacter[playerid], 400.000000, 116.500000);
	PlayerTextDrawSetOutline(playerid, LoginCharacter[playerid], 0);
	PlayerTextDrawSetShadow(playerid, LoginCharacter[playerid], 0);
	PlayerTextDrawAlignment(playerid, LoginCharacter[playerid], 2);
	PlayerTextDrawColor(playerid, LoginCharacter[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, LoginCharacter[playerid], 255);
	PlayerTextDrawBoxColor(playerid, LoginCharacter[playerid], 50);
	PlayerTextDrawUseBox(playerid, LoginCharacter[playerid], 0);
	PlayerTextDrawSetProportional(playerid, LoginCharacter[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, LoginCharacter[playerid], 0);

	LoginUCP[playerid] = CreatePlayerTextDraw(playerid, 316.000000, 200.500000, "Hash");
	PlayerTextDrawFont(playerid, LoginUCP[playerid], 2);
	PlayerTextDrawLetterSize(playerid, LoginUCP[playerid], 0.200000, 1.100000);
	PlayerTextDrawTextSize(playerid, LoginUCP[playerid], 400.000000, 116.500000);
	PlayerTextDrawSetOutline(playerid, LoginUCP[playerid], 0);
	PlayerTextDrawSetShadow(playerid, LoginUCP[playerid], 0);
	PlayerTextDrawAlignment(playerid, LoginUCP[playerid], 2);
	PlayerTextDrawColor(playerid, LoginUCP[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, LoginUCP[playerid], 255);
	PlayerTextDrawBoxColor(playerid, LoginUCP[playerid], 50);
	PlayerTextDrawUseBox(playerid, LoginUCP[playerid], 0);
	PlayerTextDrawSetProportional(playerid, LoginUCP[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, LoginUCP[playerid], 0);
}