CreateRadialTextDraws(playerid)
{
    RadialCloseButton[playerid] = CreatePlayerTextDraw(playerid, 208.000000, 185.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, RadialCloseButton[playerid], 4);
	PlayerTextDrawLetterSize(playerid, RadialCloseButton[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialCloseButton[playerid], 60.000000, 60.000000);
	PlayerTextDrawSetOutline(playerid, RadialCloseButton[playerid], 1);
	PlayerTextDrawSetShadow(playerid, RadialCloseButton[playerid], 0);
	PlayerTextDrawAlignment(playerid, RadialCloseButton[playerid], 1);
	PlayerTextDrawColor(playerid, RadialCloseButton[playerid], 673720575);
	PlayerTextDrawBackgroundColor(playerid, RadialCloseButton[playerid], 255);
	PlayerTextDrawBoxColor(playerid, RadialCloseButton[playerid], 50);
	PlayerTextDrawUseBox(playerid, RadialCloseButton[playerid], 1);
	PlayerTextDrawSetProportional(playerid, RadialCloseButton[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, RadialCloseButton[playerid], 1);

	RadialButton[playerid][0] = CreatePlayerTextDraw(playerid, 85.000000, 135.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, RadialButton[playerid][0], 4);
	PlayerTextDrawLetterSize(playerid, RadialButton[playerid][0], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialButton[playerid][0], 60.000000, 60.000000);
	PlayerTextDrawSetOutline(playerid, RadialButton[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, RadialButton[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, RadialButton[playerid][0], 1);
	PlayerTextDrawColor(playerid, RadialButton[playerid][0], 1889985279);
	PlayerTextDrawBackgroundColor(playerid, RadialButton[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, RadialButton[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, RadialButton[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, RadialButton[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, RadialButton[playerid][0], 1);

	RadialButton[playerid][1] = CreatePlayerTextDraw(playerid, 135.000000, 135.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, RadialButton[playerid][1], 4);
	PlayerTextDrawLetterSize(playerid, RadialButton[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialButton[playerid][1], 60.000000, 60.000000);
	PlayerTextDrawSetOutline(playerid, RadialButton[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, RadialButton[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, RadialButton[playerid][1], 1);
	PlayerTextDrawColor(playerid, RadialButton[playerid][1], 1889985279);
	PlayerTextDrawBackgroundColor(playerid, RadialButton[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, RadialButton[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, RadialButton[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, RadialButton[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, RadialButton[playerid][1], 1);

	RadialButton[playerid][2] = CreatePlayerTextDraw(playerid, 185.000000, 135.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, RadialButton[playerid][2], 4);
	PlayerTextDrawLetterSize(playerid, RadialButton[playerid][2], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialButton[playerid][2], 60.000000, 60.000000);
	PlayerTextDrawSetOutline(playerid, RadialButton[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, RadialButton[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, RadialButton[playerid][2], 1);
	PlayerTextDrawColor(playerid, RadialButton[playerid][2], 1889985279);
	PlayerTextDrawBackgroundColor(playerid, RadialButton[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, RadialButton[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, RadialButton[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, RadialButton[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, RadialButton[playerid][2], 1);

	RadialButton[playerid][3] = CreatePlayerTextDraw(playerid, 112.000000, 185.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, RadialButton[playerid][3], 4);
	PlayerTextDrawLetterSize(playerid, RadialButton[playerid][3], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialButton[playerid][3], 60.000000, 60.000000);
	PlayerTextDrawSetOutline(playerid, RadialButton[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, RadialButton[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, RadialButton[playerid][3], 1);
	PlayerTextDrawColor(playerid, RadialButton[playerid][3], 1889985279);
	PlayerTextDrawBackgroundColor(playerid, RadialButton[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, RadialButton[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, RadialButton[playerid][3], 1);
	PlayerTextDrawSetProportional(playerid, RadialButton[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, RadialButton[playerid][3], 1);

	RadialButton[playerid][4] = CreatePlayerTextDraw(playerid, 160.000000, 185.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, RadialButton[playerid][4], 4);
	PlayerTextDrawLetterSize(playerid, RadialButton[playerid][4], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialButton[playerid][4], 60.000000, 60.000000);
	PlayerTextDrawSetOutline(playerid, RadialButton[playerid][4], 1);
	PlayerTextDrawSetShadow(playerid, RadialButton[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, RadialButton[playerid][4], 1);
	PlayerTextDrawColor(playerid, RadialButton[playerid][4], 1889985279);
	PlayerTextDrawBackgroundColor(playerid, RadialButton[playerid][4], 255);
	PlayerTextDrawBoxColor(playerid, RadialButton[playerid][4], 50);
	PlayerTextDrawUseBox(playerid, RadialButton[playerid][4], 1);
	PlayerTextDrawSetProportional(playerid, RadialButton[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, RadialButton[playerid][4], 1);

	RadialButton[playerid][5] = CreatePlayerTextDraw(playerid, 235.000000, 135.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, RadialButton[playerid][5], 4);
	PlayerTextDrawLetterSize(playerid, RadialButton[playerid][5], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialButton[playerid][5], 60.000000, 60.000000);
	PlayerTextDrawSetOutline(playerid, RadialButton[playerid][5], 1);
	PlayerTextDrawSetShadow(playerid, RadialButton[playerid][5], 0);
	PlayerTextDrawAlignment(playerid, RadialButton[playerid][5], 1);
	PlayerTextDrawColor(playerid, RadialButton[playerid][5], 1889985279);
	PlayerTextDrawBackgroundColor(playerid, RadialButton[playerid][5], 255);
	PlayerTextDrawBoxColor(playerid, RadialButton[playerid][5], 50);
	PlayerTextDrawUseBox(playerid, RadialButton[playerid][5], 1);
	PlayerTextDrawSetProportional(playerid, RadialButton[playerid][5], 1);
	PlayerTextDrawSetSelectable(playerid, RadialButton[playerid][5], 1);

	RadialCloseIcon[playerid] = CreatePlayerTextDraw(playerid, 237.500000, 204.500000, "X");
	PlayerTextDrawFont(playerid, RadialCloseIcon[playerid], 1);
	PlayerTextDrawLetterSize(playerid, RadialCloseIcon[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialCloseIcon[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, RadialCloseIcon[playerid], 0);
	PlayerTextDrawSetShadow(playerid, RadialCloseIcon[playerid], 0);
	PlayerTextDrawAlignment(playerid, RadialCloseIcon[playerid], 2);
	PlayerTextDrawColor(playerid, RadialCloseIcon[playerid], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, RadialCloseIcon[playerid], 255);
	PlayerTextDrawBoxColor(playerid, RadialCloseIcon[playerid], 50);
	PlayerTextDrawUseBox(playerid, RadialCloseIcon[playerid], 0);
	PlayerTextDrawSetProportional(playerid, RadialCloseIcon[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, RadialCloseIcon[playerid], 0);

	RadialAccessoriesIcon[playerid][0] = CreatePlayerTextDraw(playerid, 180.000000, 198.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, RadialAccessoriesIcon[playerid][0], 4);
	PlayerTextDrawLetterSize(playerid, RadialAccessoriesIcon[playerid][0], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialAccessoriesIcon[playerid][0], 20.000000, 20.000000);
	PlayerTextDrawSetOutline(playerid, RadialAccessoriesIcon[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, RadialAccessoriesIcon[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, RadialAccessoriesIcon[playerid][0], 1);
	PlayerTextDrawColor(playerid, RadialAccessoriesIcon[playerid][0], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, RadialAccessoriesIcon[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, RadialAccessoriesIcon[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, RadialAccessoriesIcon[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, RadialAccessoriesIcon[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, RadialAccessoriesIcon[playerid][0], 0);

	RadialAccessoriesIcon[playerid][1] = CreatePlayerTextDraw(playerid, 175.000000, 213.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, RadialAccessoriesIcon[playerid][1], 4);
	PlayerTextDrawLetterSize(playerid, RadialAccessoriesIcon[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialAccessoriesIcon[playerid][1], 30.000000, 20.000000);
	PlayerTextDrawSetOutline(playerid, RadialAccessoriesIcon[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, RadialAccessoriesIcon[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, RadialAccessoriesIcon[playerid][1], 1);
	PlayerTextDrawColor(playerid, RadialAccessoriesIcon[playerid][1], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, RadialAccessoriesIcon[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, RadialAccessoriesIcon[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, RadialAccessoriesIcon[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, RadialAccessoriesIcon[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, RadialAccessoriesIcon[playerid][1], 0);

	RadialPhoneIcon[playerid][0] = CreatePlayerTextDraw(playerid, 107.000000, 152.600006, "ld_dual:white");
	PlayerTextDrawFont(playerid, RadialPhoneIcon[playerid][0], 4);
	PlayerTextDrawLetterSize(playerid, RadialPhoneIcon[playerid][0], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialPhoneIcon[playerid][0], 1.500000, 22.299999);
	PlayerTextDrawSetOutline(playerid, RadialPhoneIcon[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, RadialPhoneIcon[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, RadialPhoneIcon[playerid][0], 1);
	PlayerTextDrawColor(playerid, RadialPhoneIcon[playerid][0], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, RadialPhoneIcon[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, RadialPhoneIcon[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, RadialPhoneIcon[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, RadialPhoneIcon[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, RadialPhoneIcon[playerid][0], 0);

	RadialPhoneIcon[playerid][1] = CreatePlayerTextDraw(playerid, 120.000000, 152.600006, "ld_dual:white");
	PlayerTextDrawFont(playerid, RadialPhoneIcon[playerid][1], 4);
	PlayerTextDrawLetterSize(playerid, RadialPhoneIcon[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialPhoneIcon[playerid][1], 1.500000, 22.299999);
	PlayerTextDrawSetOutline(playerid, RadialPhoneIcon[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, RadialPhoneIcon[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, RadialPhoneIcon[playerid][1], 1);
	PlayerTextDrawColor(playerid, RadialPhoneIcon[playerid][1], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, RadialPhoneIcon[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, RadialPhoneIcon[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, RadialPhoneIcon[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, RadialPhoneIcon[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, RadialPhoneIcon[playerid][1], 0);

	RadialPhoneIcon[playerid][2] = CreatePlayerTextDraw(playerid, 108.000000, 172.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, RadialPhoneIcon[playerid][2], 4);
	PlayerTextDrawLetterSize(playerid, RadialPhoneIcon[playerid][2], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialPhoneIcon[playerid][2], 12.500000, 2.500000);
	PlayerTextDrawSetOutline(playerid, RadialPhoneIcon[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, RadialPhoneIcon[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, RadialPhoneIcon[playerid][2], 1);
	PlayerTextDrawColor(playerid, RadialPhoneIcon[playerid][2], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, RadialPhoneIcon[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, RadialPhoneIcon[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, RadialPhoneIcon[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, RadialPhoneIcon[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, RadialPhoneIcon[playerid][2], 0);

	RadialPhoneIcon[playerid][3] = CreatePlayerTextDraw(playerid, 108.000000, 152.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, RadialPhoneIcon[playerid][3], 4);
	PlayerTextDrawLetterSize(playerid, RadialPhoneIcon[playerid][3], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialPhoneIcon[playerid][3], 12.500000, 2.500000);
	PlayerTextDrawSetOutline(playerid, RadialPhoneIcon[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, RadialPhoneIcon[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, RadialPhoneIcon[playerid][3], 1);
	PlayerTextDrawColor(playerid, RadialPhoneIcon[playerid][3], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, RadialPhoneIcon[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, RadialPhoneIcon[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, RadialPhoneIcon[playerid][3], 1);
	PlayerTextDrawSetProportional(playerid, RadialPhoneIcon[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, RadialPhoneIcon[playerid][3], 0);

	RadialPhoneIcon[playerid][4] = CreatePlayerTextDraw(playerid, 111.199996, 169.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, RadialPhoneIcon[playerid][4], 4);
	PlayerTextDrawLetterSize(playerid, RadialPhoneIcon[playerid][4], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialPhoneIcon[playerid][4], 6.000000, 1.700000);
	PlayerTextDrawSetOutline(playerid, RadialPhoneIcon[playerid][4], 1);
	PlayerTextDrawSetShadow(playerid, RadialPhoneIcon[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, RadialPhoneIcon[playerid][4], 1);
	PlayerTextDrawColor(playerid, RadialPhoneIcon[playerid][4], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, RadialPhoneIcon[playerid][4], 255);
	PlayerTextDrawBoxColor(playerid, RadialPhoneIcon[playerid][4], 50);
	PlayerTextDrawUseBox(playerid, RadialPhoneIcon[playerid][4], 1);
	PlayerTextDrawSetProportional(playerid, RadialPhoneIcon[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, RadialPhoneIcon[playerid][4], 0);

	RadialInvIcon[playerid][0] = CreatePlayerTextDraw(playerid, 154.199996, 172.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, RadialInvIcon[playerid][0], 4);
	PlayerTextDrawLetterSize(playerid, RadialInvIcon[playerid][0], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialInvIcon[playerid][0], 22.000000, 2.500000);
	PlayerTextDrawSetOutline(playerid, RadialInvIcon[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, RadialInvIcon[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, RadialInvIcon[playerid][0], 1);
	PlayerTextDrawColor(playerid, RadialInvIcon[playerid][0], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, RadialInvIcon[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, RadialInvIcon[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, RadialInvIcon[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, RadialInvIcon[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, RadialInvIcon[playerid][0], 0);

	RadialInvIcon[playerid][1] = CreatePlayerTextDraw(playerid, 154.199996, 157.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, RadialInvIcon[playerid][1], 4);
	PlayerTextDrawLetterSize(playerid, RadialInvIcon[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialInvIcon[playerid][1], 22.000000, 2.500000);
	PlayerTextDrawSetOutline(playerid, RadialInvIcon[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, RadialInvIcon[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, RadialInvIcon[playerid][1], 1);
	PlayerTextDrawColor(playerid, RadialInvIcon[playerid][1], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, RadialInvIcon[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, RadialInvIcon[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, RadialInvIcon[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, RadialInvIcon[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, RadialInvIcon[playerid][1], 0);

	RadialInvIcon[playerid][2] = CreatePlayerTextDraw(playerid, 154.199996, 157.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, RadialInvIcon[playerid][2], 4);
	PlayerTextDrawLetterSize(playerid, RadialInvIcon[playerid][2], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialInvIcon[playerid][2], 2.000000, 16.000000);
	PlayerTextDrawSetOutline(playerid, RadialInvIcon[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, RadialInvIcon[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, RadialInvIcon[playerid][2], 1);
	PlayerTextDrawColor(playerid, RadialInvIcon[playerid][2], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, RadialInvIcon[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, RadialInvIcon[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, RadialInvIcon[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, RadialInvIcon[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, RadialInvIcon[playerid][2], 0);

	RadialInvIcon[playerid][3] = CreatePlayerTextDraw(playerid, 174.199996, 157.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, RadialInvIcon[playerid][3], 4);
	PlayerTextDrawLetterSize(playerid, RadialInvIcon[playerid][3], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialInvIcon[playerid][3], 2.000000, 16.000000);
	PlayerTextDrawSetOutline(playerid, RadialInvIcon[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, RadialInvIcon[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, RadialInvIcon[playerid][3], 1);
	PlayerTextDrawColor(playerid, RadialInvIcon[playerid][3], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, RadialInvIcon[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, RadialInvIcon[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, RadialInvIcon[playerid][3], 1);
	PlayerTextDrawSetProportional(playerid, RadialInvIcon[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, RadialInvIcon[playerid][3], 0);

	RadialInvIcon[playerid][4] = CreatePlayerTextDraw(playerid, 160.199996, 154.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, RadialInvIcon[playerid][4], 4);
	PlayerTextDrawLetterSize(playerid, RadialInvIcon[playerid][4], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialInvIcon[playerid][4], 2.000000, 5.500000);
	PlayerTextDrawSetOutline(playerid, RadialInvIcon[playerid][4], 1);
	PlayerTextDrawSetShadow(playerid, RadialInvIcon[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, RadialInvIcon[playerid][4], 1);
	PlayerTextDrawColor(playerid, RadialInvIcon[playerid][4], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, RadialInvIcon[playerid][4], 255);
	PlayerTextDrawBoxColor(playerid, RadialInvIcon[playerid][4], 50);
	PlayerTextDrawUseBox(playerid, RadialInvIcon[playerid][4], 1);
	PlayerTextDrawSetProportional(playerid, RadialInvIcon[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, RadialInvIcon[playerid][4], 0);

	RadialInvIcon[playerid][5] = CreatePlayerTextDraw(playerid, 168.199996, 154.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, RadialInvIcon[playerid][5], 4);
	PlayerTextDrawLetterSize(playerid, RadialInvIcon[playerid][5], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialInvIcon[playerid][5], 2.000000, 5.500000);
	PlayerTextDrawSetOutline(playerid, RadialInvIcon[playerid][5], 1);
	PlayerTextDrawSetShadow(playerid, RadialInvIcon[playerid][5], 0);
	PlayerTextDrawAlignment(playerid, RadialInvIcon[playerid][5], 1);
	PlayerTextDrawColor(playerid, RadialInvIcon[playerid][5], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, RadialInvIcon[playerid][5], 255);
	PlayerTextDrawBoxColor(playerid, RadialInvIcon[playerid][5], 50);
	PlayerTextDrawUseBox(playerid, RadialInvIcon[playerid][5], 1);
	PlayerTextDrawSetProportional(playerid, RadialInvIcon[playerid][5], 1);
	PlayerTextDrawSetSelectable(playerid, RadialInvIcon[playerid][5], 0);

	RadialInvIcon[playerid][6] = CreatePlayerTextDraw(playerid, 161.000000, 153.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, RadialInvIcon[playerid][6], 4);
	PlayerTextDrawLetterSize(playerid, RadialInvIcon[playerid][6], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialInvIcon[playerid][6], 8.500000, 2.000000);
	PlayerTextDrawSetOutline(playerid, RadialInvIcon[playerid][6], 1);
	PlayerTextDrawSetShadow(playerid, RadialInvIcon[playerid][6], 0);
	PlayerTextDrawAlignment(playerid, RadialInvIcon[playerid][6], 1);
	PlayerTextDrawColor(playerid, RadialInvIcon[playerid][6], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, RadialInvIcon[playerid][6], 255);
	PlayerTextDrawBoxColor(playerid, RadialInvIcon[playerid][6], 50);
	PlayerTextDrawUseBox(playerid, RadialInvIcon[playerid][6], 1);
	PlayerTextDrawSetProportional(playerid, RadialInvIcon[playerid][6], 1);
	PlayerTextDrawSetSelectable(playerid, RadialInvIcon[playerid][6], 0);

	RadialInvIcon[playerid][7] = CreatePlayerTextDraw(playerid, 157.000000, 159.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, RadialInvIcon[playerid][7], 4);
	PlayerTextDrawLetterSize(playerid, RadialInvIcon[playerid][7], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialInvIcon[playerid][7], 16.500000, 13.000000);
	PlayerTextDrawSetOutline(playerid, RadialInvIcon[playerid][7], 1);
	PlayerTextDrawSetShadow(playerid, RadialInvIcon[playerid][7], 0);
	PlayerTextDrawAlignment(playerid, RadialInvIcon[playerid][7], 1);
	PlayerTextDrawColor(playerid, RadialInvIcon[playerid][7], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, RadialInvIcon[playerid][7], 255);
	PlayerTextDrawBoxColor(playerid, RadialInvIcon[playerid][7], 50);
	PlayerTextDrawUseBox(playerid, RadialInvIcon[playerid][7], 1);
	PlayerTextDrawSetProportional(playerid, RadialInvIcon[playerid][7], 1);
	PlayerTextDrawSetSelectable(playerid, RadialInvIcon[playerid][7], 0);

	RadialInvIcon[playerid][8] = CreatePlayerTextDraw(playerid, 165.000000, 162.000000, "FD");
	PlayerTextDrawFont(playerid, RadialInvIcon[playerid][8], 3);
	PlayerTextDrawLetterSize(playerid, RadialInvIcon[playerid][8], 0.237498, 0.949998);
	PlayerTextDrawTextSize(playerid, RadialInvIcon[playerid][8], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, RadialInvIcon[playerid][8], 0);
	PlayerTextDrawSetShadow(playerid, RadialInvIcon[playerid][8], 0);
	PlayerTextDrawAlignment(playerid, RadialInvIcon[playerid][8], 2);
	PlayerTextDrawColor(playerid, RadialInvIcon[playerid][8], 1906762495);
	PlayerTextDrawBackgroundColor(playerid, RadialInvIcon[playerid][8], 255);
	PlayerTextDrawBoxColor(playerid, RadialInvIcon[playerid][8], 50);
	PlayerTextDrawUseBox(playerid, RadialInvIcon[playerid][8], 0);
	PlayerTextDrawSetProportional(playerid, RadialInvIcon[playerid][8], 1);
	PlayerTextDrawSetSelectable(playerid, RadialInvIcon[playerid][8], 0);

	RadialCardIcon[playerid][0] = CreatePlayerTextDraw(playerid, 202.500000, 157.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, RadialCardIcon[playerid][0], 4);
	PlayerTextDrawLetterSize(playerid, RadialCardIcon[playerid][0], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialCardIcon[playerid][0], 26.000000, 16.000000);
	PlayerTextDrawSetOutline(playerid, RadialCardIcon[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, RadialCardIcon[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, RadialCardIcon[playerid][0], 1);
	PlayerTextDrawColor(playerid, RadialCardIcon[playerid][0], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, RadialCardIcon[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, RadialCardIcon[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, RadialCardIcon[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, RadialCardIcon[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, RadialCardIcon[playerid][0], 0);

	RadialCardIcon[playerid][1] = CreatePlayerTextDraw(playerid, 204.500000, 159.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, RadialCardIcon[playerid][1], 4);
	PlayerTextDrawLetterSize(playerid, RadialCardIcon[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialCardIcon[playerid][1], 22.500000, 2.500000);
	PlayerTextDrawSetOutline(playerid, RadialCardIcon[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, RadialCardIcon[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, RadialCardIcon[playerid][1], 1);
	PlayerTextDrawColor(playerid, RadialCardIcon[playerid][1], 1906762495);
	PlayerTextDrawBackgroundColor(playerid, RadialCardIcon[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, RadialCardIcon[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, RadialCardIcon[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, RadialCardIcon[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, RadialCardIcon[playerid][1], 0);

	RadialCardIcon[playerid][2] = CreatePlayerTextDraw(playerid, 215.500000, 164.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, RadialCardIcon[playerid][2], 4);
	PlayerTextDrawLetterSize(playerid, RadialCardIcon[playerid][2], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialCardIcon[playerid][2], 11.000000, 2.000000);
	PlayerTextDrawSetOutline(playerid, RadialCardIcon[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, RadialCardIcon[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, RadialCardIcon[playerid][2], 1);
	PlayerTextDrawColor(playerid, RadialCardIcon[playerid][2], 1906762495);
	PlayerTextDrawBackgroundColor(playerid, RadialCardIcon[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, RadialCardIcon[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, RadialCardIcon[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, RadialCardIcon[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, RadialCardIcon[playerid][2], 0);

	RadialCardIcon[playerid][3] = CreatePlayerTextDraw(playerid, 215.500000, 168.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, RadialCardIcon[playerid][3], 4);
	PlayerTextDrawLetterSize(playerid, RadialCardIcon[playerid][3], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialCardIcon[playerid][3], 11.000000, 2.000000);
	PlayerTextDrawSetOutline(playerid, RadialCardIcon[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, RadialCardIcon[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, RadialCardIcon[playerid][3], 1);
	PlayerTextDrawColor(playerid, RadialCardIcon[playerid][3], 1906762495);
	PlayerTextDrawBackgroundColor(playerid, RadialCardIcon[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, RadialCardIcon[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, RadialCardIcon[playerid][3], 1);
	PlayerTextDrawSetProportional(playerid, RadialCardIcon[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, RadialCardIcon[playerid][3], 0);

	RadialCardIcon[playerid][4] = CreatePlayerTextDraw(playerid, 207.000000, 162.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, RadialCardIcon[playerid][4], 4);
	PlayerTextDrawLetterSize(playerid, RadialCardIcon[playerid][4], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialCardIcon[playerid][4], 5.000000, 5.000000);
	PlayerTextDrawSetOutline(playerid, RadialCardIcon[playerid][4], 1);
	PlayerTextDrawSetShadow(playerid, RadialCardIcon[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, RadialCardIcon[playerid][4], 1);
	PlayerTextDrawColor(playerid, RadialCardIcon[playerid][4], 1906762495);
	PlayerTextDrawBackgroundColor(playerid, RadialCardIcon[playerid][4], 255);
	PlayerTextDrawBoxColor(playerid, RadialCardIcon[playerid][4], 50);
	PlayerTextDrawUseBox(playerid, RadialCardIcon[playerid][4], 1);
	PlayerTextDrawSetProportional(playerid, RadialCardIcon[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, RadialCardIcon[playerid][4], 0);

	RadialCardIcon[playerid][5] = CreatePlayerTextDraw(playerid, 204.500000, 166.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, RadialCardIcon[playerid][5], 4);
	PlayerTextDrawLetterSize(playerid, RadialCardIcon[playerid][5], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialCardIcon[playerid][5], 10.000000, 5.000000);
	PlayerTextDrawSetOutline(playerid, RadialCardIcon[playerid][5], 1);
	PlayerTextDrawSetShadow(playerid, RadialCardIcon[playerid][5], 0);
	PlayerTextDrawAlignment(playerid, RadialCardIcon[playerid][5], 1);
	PlayerTextDrawColor(playerid, RadialCardIcon[playerid][5], 1906762495);
	PlayerTextDrawBackgroundColor(playerid, RadialCardIcon[playerid][5], 255);
	PlayerTextDrawBoxColor(playerid, RadialCardIcon[playerid][5], 50);
	PlayerTextDrawUseBox(playerid, RadialCardIcon[playerid][5], 1);
	PlayerTextDrawSetProportional(playerid, RadialCardIcon[playerid][5], 1);
	PlayerTextDrawSetSelectable(playerid, RadialCardIcon[playerid][5], 0);

	RadialVehicleIcon[playerid][0] = CreatePlayerTextDraw(playerid, 134.000000, 211.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, RadialVehicleIcon[playerid][0], 4);
	PlayerTextDrawLetterSize(playerid, RadialVehicleIcon[playerid][0], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialVehicleIcon[playerid][0], 16.500000, 9.000000);
	PlayerTextDrawSetOutline(playerid, RadialVehicleIcon[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, RadialVehicleIcon[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, RadialVehicleIcon[playerid][0], 1);
	PlayerTextDrawColor(playerid, RadialVehicleIcon[playerid][0], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, RadialVehicleIcon[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, RadialVehicleIcon[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, RadialVehicleIcon[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, RadialVehicleIcon[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, RadialVehicleIcon[playerid][0], 0);

	RadialVehicleIcon[playerid][1] = CreatePlayerTextDraw(playerid, 144.500000, 209.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, RadialVehicleIcon[playerid][1], 4);
	PlayerTextDrawLetterSize(playerid, RadialVehicleIcon[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialVehicleIcon[playerid][1], 11.000000, 13.000000);
	PlayerTextDrawSetOutline(playerid, RadialVehicleIcon[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, RadialVehicleIcon[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, RadialVehicleIcon[playerid][1], 1);
	PlayerTextDrawColor(playerid, RadialVehicleIcon[playerid][1], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, RadialVehicleIcon[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, RadialVehicleIcon[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, RadialVehicleIcon[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, RadialVehicleIcon[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, RadialVehicleIcon[playerid][1], 0);

	RadialVehicleIcon[playerid][2] = CreatePlayerTextDraw(playerid, 128.500000, 209.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, RadialVehicleIcon[playerid][2], 4);
	PlayerTextDrawLetterSize(playerid, RadialVehicleIcon[playerid][2], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialVehicleIcon[playerid][2], 11.000000, 13.000000);
	PlayerTextDrawSetOutline(playerid, RadialVehicleIcon[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, RadialVehicleIcon[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, RadialVehicleIcon[playerid][2], 1);
	PlayerTextDrawColor(playerid, RadialVehicleIcon[playerid][2], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, RadialVehicleIcon[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, RadialVehicleIcon[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, RadialVehicleIcon[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, RadialVehicleIcon[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, RadialVehicleIcon[playerid][2], 0);

	RadialVehicleIcon[playerid][3] = CreatePlayerTextDraw(playerid, 149.000000, 217.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, RadialVehicleIcon[playerid][3], 4);
	PlayerTextDrawLetterSize(playerid, RadialVehicleIcon[playerid][3], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialVehicleIcon[playerid][3], 3.500000, 9.500000);
	PlayerTextDrawSetOutline(playerid, RadialVehicleIcon[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, RadialVehicleIcon[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, RadialVehicleIcon[playerid][3], 1);
	PlayerTextDrawColor(playerid, RadialVehicleIcon[playerid][3], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, RadialVehicleIcon[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, RadialVehicleIcon[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, RadialVehicleIcon[playerid][3], 1);
	PlayerTextDrawSetProportional(playerid, RadialVehicleIcon[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, RadialVehicleIcon[playerid][3], 1);

	RadialVehicleIcon[playerid][4] = CreatePlayerTextDraw(playerid, 131.500000, 217.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, RadialVehicleIcon[playerid][4], 4);
	PlayerTextDrawLetterSize(playerid, RadialVehicleIcon[playerid][4], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialVehicleIcon[playerid][4], 3.500000, 9.500000);
	PlayerTextDrawSetOutline(playerid, RadialVehicleIcon[playerid][4], 1);
	PlayerTextDrawSetShadow(playerid, RadialVehicleIcon[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, RadialVehicleIcon[playerid][4], 1);
	PlayerTextDrawColor(playerid, RadialVehicleIcon[playerid][4], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, RadialVehicleIcon[playerid][4], 255);
	PlayerTextDrawBoxColor(playerid, RadialVehicleIcon[playerid][4], 50);
	PlayerTextDrawUseBox(playerid, RadialVehicleIcon[playerid][4], 1);
	PlayerTextDrawSetProportional(playerid, RadialVehicleIcon[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, RadialVehicleIcon[playerid][4], 0);

	RadialVehicleIcon[playerid][5] = CreatePlayerTextDraw(playerid, 149.000000, 203.000000, "\\");
	PlayerTextDrawFont(playerid, RadialVehicleIcon[playerid][5], 1);
	PlayerTextDrawLetterSize(playerid, RadialVehicleIcon[playerid][5], 0.341666, 0.949998);
	PlayerTextDrawTextSize(playerid, RadialVehicleIcon[playerid][5], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, RadialVehicleIcon[playerid][5], 0);
	PlayerTextDrawSetShadow(playerid, RadialVehicleIcon[playerid][5], 0);
	PlayerTextDrawAlignment(playerid, RadialVehicleIcon[playerid][5], 2);
	PlayerTextDrawColor(playerid, RadialVehicleIcon[playerid][5], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, RadialVehicleIcon[playerid][5], 255);
	PlayerTextDrawBoxColor(playerid, RadialVehicleIcon[playerid][5], 50);
	PlayerTextDrawUseBox(playerid, RadialVehicleIcon[playerid][5], 0);
	PlayerTextDrawSetProportional(playerid, RadialVehicleIcon[playerid][5], 1);
	PlayerTextDrawSetSelectable(playerid, RadialVehicleIcon[playerid][5], 0);

	RadialVehicleIcon[playerid][6] = CreatePlayerTextDraw(playerid, 131.500000, 212.500000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, RadialVehicleIcon[playerid][6], 4);
	PlayerTextDrawLetterSize(playerid, RadialVehicleIcon[playerid][6], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialVehicleIcon[playerid][6], 6.500000, 6.500000);
	PlayerTextDrawSetOutline(playerid, RadialVehicleIcon[playerid][6], 1);
	PlayerTextDrawSetShadow(playerid, RadialVehicleIcon[playerid][6], 0);
	PlayerTextDrawAlignment(playerid, RadialVehicleIcon[playerid][6], 1);
	PlayerTextDrawColor(playerid, RadialVehicleIcon[playerid][6], 1906631679);
	PlayerTextDrawBackgroundColor(playerid, RadialVehicleIcon[playerid][6], 255);
	PlayerTextDrawBoxColor(playerid, RadialVehicleIcon[playerid][6], 50);
	PlayerTextDrawUseBox(playerid, RadialVehicleIcon[playerid][6], 1);
	PlayerTextDrawSetProportional(playerid, RadialVehicleIcon[playerid][6], 1);
	PlayerTextDrawSetSelectable(playerid, RadialVehicleIcon[playerid][6], 0);

	RadialVehicleIcon[playerid][7] = CreatePlayerTextDraw(playerid, 135.500000, 204.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, RadialVehicleIcon[playerid][7], 4);
	PlayerTextDrawLetterSize(playerid, RadialVehicleIcon[playerid][7], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialVehicleIcon[playerid][7], 13.500000, 1.500000);
	PlayerTextDrawSetOutline(playerid, RadialVehicleIcon[playerid][7], 1);
	PlayerTextDrawSetShadow(playerid, RadialVehicleIcon[playerid][7], 0);
	PlayerTextDrawAlignment(playerid, RadialVehicleIcon[playerid][7], 1);
	PlayerTextDrawColor(playerid, RadialVehicleIcon[playerid][7], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, RadialVehicleIcon[playerid][7], 255);
	PlayerTextDrawBoxColor(playerid, RadialVehicleIcon[playerid][7], 50);
	PlayerTextDrawUseBox(playerid, RadialVehicleIcon[playerid][7], 1);
	PlayerTextDrawSetProportional(playerid, RadialVehicleIcon[playerid][7], 1);
	PlayerTextDrawSetSelectable(playerid, RadialVehicleIcon[playerid][7], 0);

	RadialVehicleIcon[playerid][8] = CreatePlayerTextDraw(playerid, 135.000000, 203.000000, "/");
	PlayerTextDrawFont(playerid, RadialVehicleIcon[playerid][8], 1);
	PlayerTextDrawLetterSize(playerid, RadialVehicleIcon[playerid][8], 0.341666, 0.949998);
	PlayerTextDrawTextSize(playerid, RadialVehicleIcon[playerid][8], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, RadialVehicleIcon[playerid][8], 0);
	PlayerTextDrawSetShadow(playerid, RadialVehicleIcon[playerid][8], 0);
	PlayerTextDrawAlignment(playerid, RadialVehicleIcon[playerid][8], 2);
	PlayerTextDrawColor(playerid, RadialVehicleIcon[playerid][8], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, RadialVehicleIcon[playerid][8], 255);
	PlayerTextDrawBoxColor(playerid, RadialVehicleIcon[playerid][8], 50);
	PlayerTextDrawUseBox(playerid, RadialVehicleIcon[playerid][8], 0);
	PlayerTextDrawSetProportional(playerid, RadialVehicleIcon[playerid][8], 1);
	PlayerTextDrawSetSelectable(playerid, RadialVehicleIcon[playerid][8], 0);

	RadialVehicleIcon[playerid][9] = CreatePlayerTextDraw(playerid, 146.500000, 212.500000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, RadialVehicleIcon[playerid][9], 4);
	PlayerTextDrawLetterSize(playerid, RadialVehicleIcon[playerid][9], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialVehicleIcon[playerid][9], 6.500000, 6.500000);
	PlayerTextDrawSetOutline(playerid, RadialVehicleIcon[playerid][9], 1);
	PlayerTextDrawSetShadow(playerid, RadialVehicleIcon[playerid][9], 0);
	PlayerTextDrawAlignment(playerid, RadialVehicleIcon[playerid][9], 1);
	PlayerTextDrawColor(playerid, RadialVehicleIcon[playerid][9], 1906631679);
	PlayerTextDrawBackgroundColor(playerid, RadialVehicleIcon[playerid][9], 255);
	PlayerTextDrawBoxColor(playerid, RadialVehicleIcon[playerid][9], 50);
	PlayerTextDrawUseBox(playerid, RadialVehicleIcon[playerid][9], 1);
	PlayerTextDrawSetProportional(playerid, RadialVehicleIcon[playerid][9], 1);
	PlayerTextDrawSetSelectable(playerid, RadialVehicleIcon[playerid][9], 0);

	RadialVehicleIcon[playerid][10] = CreatePlayerTextDraw(playerid, 150.000000, 206.500000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, RadialVehicleIcon[playerid][10], 4);
	PlayerTextDrawLetterSize(playerid, RadialVehicleIcon[playerid][10], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialVehicleIcon[playerid][10], 5.000000, 5.000000);
	PlayerTextDrawSetOutline(playerid, RadialVehicleIcon[playerid][10], 1);
	PlayerTextDrawSetShadow(playerid, RadialVehicleIcon[playerid][10], 0);
	PlayerTextDrawAlignment(playerid, RadialVehicleIcon[playerid][10], 1);
	PlayerTextDrawColor(playerid, RadialVehicleIcon[playerid][10], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, RadialVehicleIcon[playerid][10], 255);
	PlayerTextDrawBoxColor(playerid, RadialVehicleIcon[playerid][10], 50);
	PlayerTextDrawUseBox(playerid, RadialVehicleIcon[playerid][10], 1);
	PlayerTextDrawSetProportional(playerid, RadialVehicleIcon[playerid][10], 1);
	PlayerTextDrawSetSelectable(playerid, RadialVehicleIcon[playerid][10], 0);

	RadialVehicleIcon[playerid][11] = CreatePlayerTextDraw(playerid, 129.000000, 206.500000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, RadialVehicleIcon[playerid][11], 4);
	PlayerTextDrawLetterSize(playerid, RadialVehicleIcon[playerid][11], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialVehicleIcon[playerid][11], 5.000000, 5.000000);
	PlayerTextDrawSetOutline(playerid, RadialVehicleIcon[playerid][11], 1);
	PlayerTextDrawSetShadow(playerid, RadialVehicleIcon[playerid][11], 0);
	PlayerTextDrawAlignment(playerid, RadialVehicleIcon[playerid][11], 1);
	PlayerTextDrawColor(playerid, RadialVehicleIcon[playerid][11], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, RadialVehicleIcon[playerid][11], 255);
	PlayerTextDrawBoxColor(playerid, RadialVehicleIcon[playerid][11], 50);
	PlayerTextDrawUseBox(playerid, RadialVehicleIcon[playerid][11], 1);
	PlayerTextDrawSetProportional(playerid, RadialVehicleIcon[playerid][11], 1);
	PlayerTextDrawSetSelectable(playerid, RadialVehicleIcon[playerid][11], 0);

	RadialActionIcon[playerid][0] = CreatePlayerTextDraw(playerid, 261.000000, 149.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, RadialActionIcon[playerid][0], 4);
	PlayerTextDrawLetterSize(playerid, RadialActionIcon[playerid][0], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialActionIcon[playerid][0], 15.000000, 15.000000);
	PlayerTextDrawSetOutline(playerid, RadialActionIcon[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, RadialActionIcon[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, RadialActionIcon[playerid][0], 1);
	PlayerTextDrawColor(playerid, RadialActionIcon[playerid][0], -1061109630);
	PlayerTextDrawBackgroundColor(playerid, RadialActionIcon[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, RadialActionIcon[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, RadialActionIcon[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, RadialActionIcon[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, RadialActionIcon[playerid][0], 0);

	RadialActionIcon[playerid][1] = CreatePlayerTextDraw(playerid, 258.000000, 161.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, RadialActionIcon[playerid][1], 4);
	PlayerTextDrawLetterSize(playerid, RadialActionIcon[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialActionIcon[playerid][1], 21.000000, 15.000000);
	PlayerTextDrawSetOutline(playerid, RadialActionIcon[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, RadialActionIcon[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, RadialActionIcon[playerid][1], 1);
	PlayerTextDrawColor(playerid, RadialActionIcon[playerid][1], -1061109630);
	PlayerTextDrawBackgroundColor(playerid, RadialActionIcon[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, RadialActionIcon[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, RadialActionIcon[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, RadialActionIcon[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, RadialActionIcon[playerid][1], 0);

	RadialActionIcon[playerid][2] = CreatePlayerTextDraw(playerid, 255.000000, 152.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, RadialActionIcon[playerid][2], 4);
	PlayerTextDrawLetterSize(playerid, RadialActionIcon[playerid][2], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialActionIcon[playerid][2], 15.000000, 15.000000);
	PlayerTextDrawSetOutline(playerid, RadialActionIcon[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, RadialActionIcon[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, RadialActionIcon[playerid][2], 1);
	PlayerTextDrawColor(playerid, RadialActionIcon[playerid][2], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, RadialActionIcon[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, RadialActionIcon[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, RadialActionIcon[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, RadialActionIcon[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, RadialActionIcon[playerid][2], 0);

	RadialActionIcon[playerid][3] = CreatePlayerTextDraw(playerid, 252.000000, 164.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, RadialActionIcon[playerid][3], 4);
	PlayerTextDrawLetterSize(playerid, RadialActionIcon[playerid][3], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RadialActionIcon[playerid][3], 21.000000, 15.000000);
	PlayerTextDrawSetOutline(playerid, RadialActionIcon[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, RadialActionIcon[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, RadialActionIcon[playerid][3], 1);
	PlayerTextDrawColor(playerid, RadialActionIcon[playerid][3], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, RadialActionIcon[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, RadialActionIcon[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, RadialActionIcon[playerid][3], 1);
	PlayerTextDrawSetProportional(playerid, RadialActionIcon[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, RadialActionIcon[playerid][3], 0);
}