CreatePhoneTextDraws(playerid)
{
    PhoneTDBazzle[playerid][0] = CreatePlayerTextDraw(playerid, 462.500000, 352.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PhoneTDBazzle[playerid][0], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDBazzle[playerid][0], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDBazzle[playerid][0], 19.500000, 14.500000);
	PlayerTextDrawSetOutline(playerid, PhoneTDBazzle[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDBazzle[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDBazzle[playerid][0], 1);
	PlayerTextDrawColor(playerid, PhoneTDBazzle[playerid][0], 255);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDBazzle[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDBazzle[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDBazzle[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDBazzle[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDBazzle[playerid][0], 0);

	PhoneTDBazzle[playerid][1] = CreatePlayerTextDraw(playerid, 360.000000, 350.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PhoneTDBazzle[playerid][1], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDBazzle[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDBazzle[playerid][1], 17.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDBazzle[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDBazzle[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDBazzle[playerid][1], 1);
	PlayerTextDrawColor(playerid, PhoneTDBazzle[playerid][1], 255);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDBazzle[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDBazzle[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDBazzle[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDBazzle[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDBazzle[playerid][1], 0);

	PhoneTDBazzle[playerid][2] = CreatePlayerTextDraw(playerid, 360.000000, 133.500000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PhoneTDBazzle[playerid][2], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDBazzle[playerid][2], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDBazzle[playerid][2], 17.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDBazzle[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDBazzle[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDBazzle[playerid][2], 1);
	PlayerTextDrawColor(playerid, PhoneTDBazzle[playerid][2], 255);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDBazzle[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDBazzle[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDBazzle[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDBazzle[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDBazzle[playerid][2], 0);

	PhoneTDBazzle[playerid][3] = CreatePlayerTextDraw(playerid, 466.500000, 133.500000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PhoneTDBazzle[playerid][3], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDBazzle[playerid][3], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDBazzle[playerid][3], 15.000000, 15.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDBazzle[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDBazzle[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDBazzle[playerid][3], 1);
	PlayerTextDrawColor(playerid, PhoneTDBazzle[playerid][3], 255);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDBazzle[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDBazzle[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDBazzle[playerid][3], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDBazzle[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDBazzle[playerid][3], 0);

	PhoneTDBazzle[playerid][6] = CreatePlayerTextDraw(playerid, 367.000000, 136.300003, "ld_dual:white");
	PlayerTextDrawFont(playerid, PhoneTDBazzle[playerid][6], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDBazzle[playerid][6], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDBazzle[playerid][6], 105.500000, 5.500000);
	PlayerTextDrawSetOutline(playerid, PhoneTDBazzle[playerid][6], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDBazzle[playerid][6], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDBazzle[playerid][6], 1);
	PlayerTextDrawColor(playerid, PhoneTDBazzle[playerid][6], 255);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDBazzle[playerid][6], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDBazzle[playerid][6], 673720575);
	PlayerTextDrawUseBox(playerid, PhoneTDBazzle[playerid][6], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDBazzle[playerid][6], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDBazzle[playerid][6], 0);

	PhoneTDBazzle[playerid][4] = CreatePlayerTextDraw(playerid, 363.000000, 143.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PhoneTDBazzle[playerid][4], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDBazzle[playerid][4], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDBazzle[playerid][4], 3.000000, 217.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDBazzle[playerid][4], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDBazzle[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDBazzle[playerid][4], 1);
	PlayerTextDrawColor(playerid, PhoneTDBazzle[playerid][4], 255);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDBazzle[playerid][4], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDBazzle[playerid][4], 673720575);
	PlayerTextDrawUseBox(playerid, PhoneTDBazzle[playerid][4], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDBazzle[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDBazzle[playerid][4], 0);

	PhoneTDBazzle[playerid][5] = CreatePlayerTextDraw(playerid, 476.000000, 140.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PhoneTDBazzle[playerid][5], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDBazzle[playerid][5], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDBazzle[playerid][5], 3.000000, 220.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDBazzle[playerid][5], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDBazzle[playerid][5], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDBazzle[playerid][5], 1);
	PlayerTextDrawColor(playerid, PhoneTDBazzle[playerid][5], 255);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDBazzle[playerid][5], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDBazzle[playerid][5], 673720575);
	PlayerTextDrawUseBox(playerid, PhoneTDBazzle[playerid][5], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDBazzle[playerid][5], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDBazzle[playerid][5], 0);

	PhoneTDBazzle[playerid][7] = CreatePlayerTextDraw(playerid, 367.000000, 360.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PhoneTDBazzle[playerid][7], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDBazzle[playerid][7], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDBazzle[playerid][7], 107.500000, 4.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDBazzle[playerid][7], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDBazzle[playerid][7], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDBazzle[playerid][7], 1);
	PlayerTextDrawColor(playerid, PhoneTDBazzle[playerid][7], 255);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDBazzle[playerid][7], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDBazzle[playerid][7], 673720575);
	PlayerTextDrawUseBox(playerid, PhoneTDBazzle[playerid][7], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDBazzle[playerid][7], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDBazzle[playerid][7], 0);

	PhoneTDScreen[playerid][1] = CreatePlayerTextDraw(playerid, 363.000000, 137.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PhoneTDScreen[playerid][1], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDScreen[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDScreen[playerid][1], 17.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDScreen[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDScreen[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDScreen[playerid][1], 1);
	PlayerTextDrawColor(playerid, PhoneTDScreen[playerid][1], 1889854207);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDScreen[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDScreen[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDScreen[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDScreen[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDScreen[playerid][1], 0);

	PhoneTDScreen[playerid][0] = CreatePlayerTextDraw(playerid, 369.500000, 147.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PhoneTDScreen[playerid][0], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDScreen[playerid][0], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDScreen[playerid][0], 103.500000, 209.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDScreen[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDScreen[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDScreen[playerid][0], 1);
	PlayerTextDrawColor(playerid, PhoneTDScreen[playerid][0], 1889854207);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDScreen[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDScreen[playerid][0], 673720575);
	PlayerTextDrawUseBox(playerid, PhoneTDScreen[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDScreen[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDScreen[playerid][0], 0);

	PhoneTDScreen[playerid][2] = CreatePlayerTextDraw(playerid, 462.000000, 137.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PhoneTDScreen[playerid][2], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDScreen[playerid][2], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDScreen[playerid][2], 17.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDScreen[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDScreen[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDScreen[playerid][2], 1);
	PlayerTextDrawColor(playerid, PhoneTDScreen[playerid][2], 1889854207);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDScreen[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDScreen[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDScreen[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDScreen[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDScreen[playerid][2], 0);

	PhoneTDScreen[playerid][3] = CreatePlayerTextDraw(playerid, 462.000000, 346.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PhoneTDScreen[playerid][3], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDScreen[playerid][3], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDScreen[playerid][3], 17.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDScreen[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDScreen[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDScreen[playerid][3], 1);
	PlayerTextDrawColor(playerid, PhoneTDScreen[playerid][3], 1889854207);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDScreen[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDScreen[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDScreen[playerid][3], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDScreen[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDScreen[playerid][3], 0);

	PhoneTDScreen[playerid][4] = CreatePlayerTextDraw(playerid, 363.000000, 346.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PhoneTDScreen[playerid][4], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDScreen[playerid][4], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDScreen[playerid][4], 17.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDScreen[playerid][4], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDScreen[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDScreen[playerid][4], 1);
	PlayerTextDrawColor(playerid, PhoneTDScreen[playerid][4], 1889854207);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDScreen[playerid][4], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDScreen[playerid][4], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDScreen[playerid][4], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDScreen[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDScreen[playerid][4], 0);

	PhoneTDScreen[playerid][5] = CreatePlayerTextDraw(playerid, 366.000000, 147.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PhoneTDScreen[playerid][5], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDScreen[playerid][5], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDScreen[playerid][5], 4.000000, 207.500000);
	PlayerTextDrawSetOutline(playerid, PhoneTDScreen[playerid][5], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDScreen[playerid][5], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDScreen[playerid][5], 1);
	PlayerTextDrawColor(playerid, PhoneTDScreen[playerid][5], 1889854207);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDScreen[playerid][5], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDScreen[playerid][5], 673720575);
	PlayerTextDrawUseBox(playerid, PhoneTDScreen[playerid][5], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDScreen[playerid][5], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDScreen[playerid][5], 0);

	PhoneTDScreen[playerid][6] = CreatePlayerTextDraw(playerid, 472.250000, 147.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PhoneTDScreen[playerid][6], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDScreen[playerid][6], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDScreen[playerid][6], 4.000000, 207.500000);
	PlayerTextDrawSetOutline(playerid, PhoneTDScreen[playerid][6], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDScreen[playerid][6], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDScreen[playerid][6], 1);
	PlayerTextDrawColor(playerid, PhoneTDScreen[playerid][6], 1889854207);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDScreen[playerid][6], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDScreen[playerid][6], 673720575);
	PlayerTextDrawUseBox(playerid, PhoneTDScreen[playerid][6], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDScreen[playerid][6], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDScreen[playerid][6], 0);

	PhoneTDScreen[playerid][7] = CreatePlayerTextDraw(playerid, 371.000000, 341.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PhoneTDScreen[playerid][7], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDScreen[playerid][7], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDScreen[playerid][7], 98.500000, 18.500000);
	PlayerTextDrawSetOutline(playerid, PhoneTDScreen[playerid][7], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDScreen[playerid][7], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDScreen[playerid][7], 1);
	PlayerTextDrawColor(playerid, PhoneTDScreen[playerid][7], 1889854207);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDScreen[playerid][7], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDScreen[playerid][7], 673720575);
	PlayerTextDrawUseBox(playerid, PhoneTDScreen[playerid][7], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDScreen[playerid][7], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDScreen[playerid][7], 0);

	PhoneTDScreen[playerid][8] = CreatePlayerTextDraw(playerid, 371.000000, 140.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PhoneTDScreen[playerid][8], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDScreen[playerid][8], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDScreen[playerid][8], 98.500000, 18.500000);
	PlayerTextDrawSetOutline(playerid, PhoneTDScreen[playerid][8], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDScreen[playerid][8], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDScreen[playerid][8], 1);
	PlayerTextDrawColor(playerid, PhoneTDScreen[playerid][8], 1889854207);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDScreen[playerid][8], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDScreen[playerid][8], 673720575);
	PlayerTextDrawUseBox(playerid, PhoneTDScreen[playerid][8], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDScreen[playerid][8], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDScreen[playerid][8], 0);

	PhoneTDDot[playerid] = CreatePlayerTextDraw(playerid, 414.000000, 141.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PhoneTDDot[playerid], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDDot[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDDot[playerid], 15.000000, 15.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDDot[playerid], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDDot[playerid], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDDot[playerid], 1);
	PlayerTextDrawColor(playerid, PhoneTDDot[playerid], 255);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDDot[playerid], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDDot[playerid], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDDot[playerid], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDDot[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDDot[playerid], 0);

	PhoneTDTime[playerid][0] = CreatePlayerTextDraw(playerid, 422.000000, 177.000000, "14:30");
	PlayerTextDrawFont(playerid, PhoneTDTime[playerid][0], 1);
	PlayerTextDrawLetterSize(playerid, PhoneTDTime[playerid][0], 0.600000, 3.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDTime[playerid][0], 400.000000, 102.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDTime[playerid][0], 0);
	PlayerTextDrawSetShadow(playerid, PhoneTDTime[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDTime[playerid][0], 2);
	PlayerTextDrawColor(playerid, PhoneTDTime[playerid][0], -1);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDTime[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDTime[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDTime[playerid][0], 0);
	PlayerTextDrawSetProportional(playerid, PhoneTDTime[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDTime[playerid][0], 0);

    PhoneTDTime[playerid][1] = CreatePlayerTextDraw(playerid, 377.000000, 143.000000, "14:30");
	PlayerTextDrawFont(playerid, PhoneTDTime[playerid][1], 1);
	PlayerTextDrawLetterSize(playerid, PhoneTDTime[playerid][1], 0.150000, 0.750001);
	PlayerTextDrawTextSize(playerid, PhoneTDTime[playerid][1], 400.000000, 102.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDTime[playerid][1], 0);
	PlayerTextDrawSetShadow(playerid, PhoneTDTime[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDTime[playerid][1], 2);
	PlayerTextDrawColor(playerid, PhoneTDTime[playerid][1], -1);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDTime[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDTime[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDTime[playerid][1], 0);
	PlayerTextDrawSetProportional(playerid, PhoneTDTime[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDTime[playerid][1], 0);

	PhoneTDDate[playerid] = CreatePlayerTextDraw(playerid, 422.000000, 204.000000, "11 August 2001");
	PlayerTextDrawFont(playerid, PhoneTDDate[playerid], 1);
	PlayerTextDrawLetterSize(playerid, PhoneTDDate[playerid], 0.200000, 1.100000);
	PlayerTextDrawTextSize(playerid, PhoneTDDate[playerid], 400.000000, 102.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDDate[playerid], 0);
	PlayerTextDrawSetShadow(playerid, PhoneTDDate[playerid], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDDate[playerid], 2);
	PlayerTextDrawColor(playerid, PhoneTDDate[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDDate[playerid], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDDate[playerid], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDDate[playerid], 0);
	PlayerTextDrawSetProportional(playerid, PhoneTDDate[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDDate[playerid], 0);

	PhoneTDButton[playerid][0] = CreatePlayerTextDraw(playerid, 387.000000, 339.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PhoneTDButton[playerid][0], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDButton[playerid][0], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDButton[playerid][0], 70.000000, 10.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDButton[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDButton[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDButton[playerid][0], 1);
	PlayerTextDrawColor(playerid, PhoneTDButton[playerid][0], -1061109635);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDButton[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDButton[playerid][0], 673720575);
	PlayerTextDrawUseBox(playerid, PhoneTDButton[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDButton[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDButton[playerid][0], 1);

    PhoneTDButton[playerid][1] = CreatePlayerTextDraw(playerid, 387.000000, 339.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PhoneTDButton[playerid][1], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDButton[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDButton[playerid][1], 70.000000, 10.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDButton[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDButton[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDButton[playerid][1], 1);
	PlayerTextDrawColor(playerid, PhoneTDButton[playerid][1], -1061109635);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDButton[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDButton[playerid][1], 673720575);
	PlayerTextDrawUseBox(playerid, PhoneTDButton[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDButton[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDButton[playerid][1], 1);

    PhoneTDApkButton[playerid][0] = CreatePlayerTextDraw(playerid, 367.000000, 167.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PhoneTDApkButton[playerid][0], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDApkButton[playerid][0], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDApkButton[playerid][0], 40.000000, 40.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDApkButton[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDApkButton[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDApkButton[playerid][0], 1);
	PlayerTextDrawColor(playerid, PhoneTDApkButton[playerid][0], 673720410);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDApkButton[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDApkButton[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDApkButton[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDApkButton[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDApkButton[playerid][0], 1);

	PhoneTDApkButton[playerid][1] = CreatePlayerTextDraw(playerid, 402.000000, 167.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PhoneTDApkButton[playerid][1], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDApkButton[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDApkButton[playerid][1], 40.000000, 40.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDApkButton[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDApkButton[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDApkButton[playerid][1], 1);
	PlayerTextDrawColor(playerid, PhoneTDApkButton[playerid][1], 673720410);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDApkButton[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDApkButton[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDApkButton[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDApkButton[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDApkButton[playerid][1], 1);

	PhoneTDApkButton[playerid][2] = CreatePlayerTextDraw(playerid, 436.000000, 167.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PhoneTDApkButton[playerid][2], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDApkButton[playerid][2], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDApkButton[playerid][2], 40.000000, 40.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDApkButton[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDApkButton[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDApkButton[playerid][2], 1);
	PlayerTextDrawColor(playerid, PhoneTDApkButton[playerid][2], 673720410);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDApkButton[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDApkButton[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDApkButton[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDApkButton[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDApkButton[playerid][2], 1);

	PhoneTDApkButton[playerid][3] = CreatePlayerTextDraw(playerid, 367.000000, 207.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PhoneTDApkButton[playerid][3], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDApkButton[playerid][3], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDApkButton[playerid][3], 40.000000, 40.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDApkButton[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDApkButton[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDApkButton[playerid][3], 1);
	PlayerTextDrawColor(playerid, PhoneTDApkButton[playerid][3], 673720410);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDApkButton[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDApkButton[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDApkButton[playerid][3], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDApkButton[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDApkButton[playerid][3], 1);

	PhoneTDApkButton[playerid][4] = CreatePlayerTextDraw(playerid, 402.000000, 207.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PhoneTDApkButton[playerid][4], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDApkButton[playerid][4], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDApkButton[playerid][4], 40.000000, 40.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDApkButton[playerid][4], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDApkButton[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDApkButton[playerid][4], 1);
	PlayerTextDrawColor(playerid, PhoneTDApkButton[playerid][4], 673720410);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDApkButton[playerid][4], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDApkButton[playerid][4], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDApkButton[playerid][4], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDApkButton[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDApkButton[playerid][4], 1);

	PhoneTDApkButton[playerid][5] = CreatePlayerTextDraw(playerid, 437.000000, 207.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PhoneTDApkButton[playerid][5], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDApkButton[playerid][5], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDApkButton[playerid][5], 40.000000, 40.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDApkButton[playerid][5], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDApkButton[playerid][5], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDApkButton[playerid][5], 1);
	PlayerTextDrawColor(playerid, PhoneTDApkButton[playerid][5], 673720410);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDApkButton[playerid][5], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDApkButton[playerid][5], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDApkButton[playerid][5], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDApkButton[playerid][5], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDApkButton[playerid][5], 1);

	PhoneTDApkButton[playerid][6] = CreatePlayerTextDraw(playerid, 367.000000, 247.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PhoneTDApkButton[playerid][6], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDApkButton[playerid][6], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDApkButton[playerid][6], 40.000000, 40.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDApkButton[playerid][6], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDApkButton[playerid][6], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDApkButton[playerid][6], 1);
	PlayerTextDrawColor(playerid, PhoneTDApkButton[playerid][6], 673720410);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDApkButton[playerid][6], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDApkButton[playerid][6], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDApkButton[playerid][6], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDApkButton[playerid][6], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDApkButton[playerid][6], 1);

	PhoneTDApkButton[playerid][7] = CreatePlayerTextDraw(playerid, 402.000000, 247.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PhoneTDApkButton[playerid][7], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDApkButton[playerid][7], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDApkButton[playerid][7], 40.000000, 40.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDApkButton[playerid][7], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDApkButton[playerid][7], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDApkButton[playerid][7], 1);
	PlayerTextDrawColor(playerid, PhoneTDApkButton[playerid][7], 673720410);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDApkButton[playerid][7], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDApkButton[playerid][7], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDApkButton[playerid][7], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDApkButton[playerid][7], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDApkButton[playerid][7], 1);

	PhoneTDApkButton[playerid][8] = CreatePlayerTextDraw(playerid, 437.000000, 247.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PhoneTDApkButton[playerid][8], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDApkButton[playerid][8], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDApkButton[playerid][8], 40.000000, 40.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDApkButton[playerid][8], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDApkButton[playerid][8], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDApkButton[playerid][8], 1);
	PlayerTextDrawColor(playerid, PhoneTDApkButton[playerid][8], 673720410);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDApkButton[playerid][8], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDApkButton[playerid][8], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDApkButton[playerid][8], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDApkButton[playerid][8], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDApkButton[playerid][8], 1);

	PhoneTDApkButton[playerid][9] = CreatePlayerTextDraw(playerid, 367.000000, 295.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PhoneTDApkButton[playerid][9], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDApkButton[playerid][9], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDApkButton[playerid][9], 40.000000, 40.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDApkButton[playerid][9], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDApkButton[playerid][9], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDApkButton[playerid][9], 1);
	PlayerTextDrawColor(playerid, PhoneTDApkButton[playerid][9], 673720395);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDApkButton[playerid][9], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDApkButton[playerid][9], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDApkButton[playerid][9], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDApkButton[playerid][9], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDApkButton[playerid][9], 1);

	PhoneTDApkButton[playerid][10] = CreatePlayerTextDraw(playerid, 402.000000, 295.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PhoneTDApkButton[playerid][10], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDApkButton[playerid][10], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDApkButton[playerid][10], 40.000000, 40.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDApkButton[playerid][10], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDApkButton[playerid][10], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDApkButton[playerid][10], 1);
	PlayerTextDrawColor(playerid, PhoneTDApkButton[playerid][10], 673720395);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDApkButton[playerid][10], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDApkButton[playerid][10], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDApkButton[playerid][10], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDApkButton[playerid][10], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDApkButton[playerid][10], 1);

	PhoneTDApkButton[playerid][11] = CreatePlayerTextDraw(playerid, 437.000000, 295.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PhoneTDApkButton[playerid][11], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDApkButton[playerid][11], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDApkButton[playerid][11], 40.000000, 40.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDApkButton[playerid][11], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDApkButton[playerid][11], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDApkButton[playerid][11], 1);
	PlayerTextDrawColor(playerid, PhoneTDApkButton[playerid][11], 673720395);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDApkButton[playerid][11], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDApkButton[playerid][11], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDApkButton[playerid][11], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDApkButton[playerid][11], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDApkButton[playerid][11], 1);

	PhoneTDApkText[playerid][0] = CreatePlayerTextDraw(playerid, 387.000000, 199.000000, "Music");
	PlayerTextDrawFont(playerid, PhoneTDApkText[playerid][0], 1);
	PlayerTextDrawLetterSize(playerid, PhoneTDApkText[playerid][0], 0.150000, 0.949998);
	PlayerTextDrawTextSize(playerid, PhoneTDApkText[playerid][0], 400.000000, 107.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDApkText[playerid][0], 0);
	PlayerTextDrawSetShadow(playerid, PhoneTDApkText[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDApkText[playerid][0], 2);
	PlayerTextDrawColor(playerid, PhoneTDApkText[playerid][0], -1);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDApkText[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDApkText[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDApkText[playerid][0], 0);
	PlayerTextDrawSetProportional(playerid, PhoneTDApkText[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDApkText[playerid][0], 0);

	PhoneTDApkText[playerid][1] = CreatePlayerTextDraw(playerid, 422.000000, 199.000000, "Job");
	PlayerTextDrawFont(playerid, PhoneTDApkText[playerid][1], 1);
	PlayerTextDrawLetterSize(playerid, PhoneTDApkText[playerid][1], 0.150000, 0.949998);
	PlayerTextDrawTextSize(playerid, PhoneTDApkText[playerid][1], 400.000000, 107.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDApkText[playerid][1], 0);
	PlayerTextDrawSetShadow(playerid, PhoneTDApkText[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDApkText[playerid][1], 2);
	PlayerTextDrawColor(playerid, PhoneTDApkText[playerid][1], -1);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDApkText[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDApkText[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDApkText[playerid][1], 0);
	PlayerTextDrawSetProportional(playerid, PhoneTDApkText[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDApkText[playerid][1], 0);

	PhoneTDApkText[playerid][2] = CreatePlayerTextDraw(playerid, 456.000000, 199.000000, "Ads");
	PlayerTextDrawFont(playerid, PhoneTDApkText[playerid][2], 1);
	PlayerTextDrawLetterSize(playerid, PhoneTDApkText[playerid][2], 0.150000, 0.949998);
	PlayerTextDrawTextSize(playerid, PhoneTDApkText[playerid][2], 400.000000, 107.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDApkText[playerid][2], 0);
	PlayerTextDrawSetShadow(playerid, PhoneTDApkText[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDApkText[playerid][2], 2);
	PlayerTextDrawColor(playerid, PhoneTDApkText[playerid][2], -1);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDApkText[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDApkText[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDApkText[playerid][2], 0);
	PlayerTextDrawSetProportional(playerid, PhoneTDApkText[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDApkText[playerid][2], 0);

	PhoneTDApkText[playerid][3] = CreatePlayerTextDraw(playerid, 387.000000, 239.000000, "M-Banking");
	PlayerTextDrawFont(playerid, PhoneTDApkText[playerid][3], 1);
	PlayerTextDrawLetterSize(playerid, PhoneTDApkText[playerid][3], 0.150000, 0.949998);
	PlayerTextDrawTextSize(playerid, PhoneTDApkText[playerid][3], 400.000000, 107.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDApkText[playerid][3], 0);
	PlayerTextDrawSetShadow(playerid, PhoneTDApkText[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDApkText[playerid][3], 2);
	PlayerTextDrawColor(playerid, PhoneTDApkText[playerid][3], -1);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDApkText[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDApkText[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDApkText[playerid][3], 0);
	PlayerTextDrawSetProportional(playerid, PhoneTDApkText[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDApkText[playerid][3], 0);

	PhoneTDApkText[playerid][4] = CreatePlayerTextDraw(playerid, 422.000000, 239.000000, "Taxi");
	PlayerTextDrawFont(playerid, PhoneTDApkText[playerid][4], 1);
	PlayerTextDrawLetterSize(playerid, PhoneTDApkText[playerid][4], 0.150000, 0.949998);
	PlayerTextDrawTextSize(playerid, PhoneTDApkText[playerid][4], 400.000000, 107.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDApkText[playerid][4], 0);
	PlayerTextDrawSetShadow(playerid, PhoneTDApkText[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDApkText[playerid][4], 2);
	PlayerTextDrawColor(playerid, PhoneTDApkText[playerid][4], -1);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDApkText[playerid][4], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDApkText[playerid][4], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDApkText[playerid][4], 0);
	PlayerTextDrawSetProportional(playerid, PhoneTDApkText[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDApkText[playerid][4], 0);

	PhoneTDApkText[playerid][5] = CreatePlayerTextDraw(playerid, 457.000000, 239.000000, "AirDrop");
	PlayerTextDrawFont(playerid, PhoneTDApkText[playerid][5], 1);
	PlayerTextDrawLetterSize(playerid, PhoneTDApkText[playerid][5], 0.150000, 0.949998);
	PlayerTextDrawTextSize(playerid, PhoneTDApkText[playerid][5], 400.000000, 107.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDApkText[playerid][5], 0);
	PlayerTextDrawSetShadow(playerid, PhoneTDApkText[playerid][5], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDApkText[playerid][5], 2);
	PlayerTextDrawColor(playerid, PhoneTDApkText[playerid][5], -1);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDApkText[playerid][5], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDApkText[playerid][5], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDApkText[playerid][5], 0);
	PlayerTextDrawSetProportional(playerid, PhoneTDApkText[playerid][5], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDApkText[playerid][5], 0);

	PhoneTDApkText[playerid][6] = CreatePlayerTextDraw(playerid, 387.000000, 279.000000, "Settings");
	PlayerTextDrawFont(playerid, PhoneTDApkText[playerid][6], 1);
	PlayerTextDrawLetterSize(playerid, PhoneTDApkText[playerid][6], 0.150000, 0.949998);
	PlayerTextDrawTextSize(playerid, PhoneTDApkText[playerid][6], 400.000000, 107.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDApkText[playerid][6], 0);
	PlayerTextDrawSetShadow(playerid, PhoneTDApkText[playerid][6], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDApkText[playerid][6], 2);
	PlayerTextDrawColor(playerid, PhoneTDApkText[playerid][6], -1);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDApkText[playerid][6], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDApkText[playerid][6], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDApkText[playerid][6], 0);
	PlayerTextDrawSetProportional(playerid, PhoneTDApkText[playerid][6], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDApkText[playerid][6], 0);

	PhoneTDApkText[playerid][7] = CreatePlayerTextDraw(playerid, 422.000000, 279.000000, "Maps");
	PlayerTextDrawFont(playerid, PhoneTDApkText[playerid][7], 1);
	PlayerTextDrawLetterSize(playerid, PhoneTDApkText[playerid][7], 0.150000, 0.949998);
	PlayerTextDrawTextSize(playerid, PhoneTDApkText[playerid][7], 400.000000, 107.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDApkText[playerid][7], 0);
	PlayerTextDrawSetShadow(playerid, PhoneTDApkText[playerid][7], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDApkText[playerid][7], 2);
	PlayerTextDrawColor(playerid, PhoneTDApkText[playerid][7], -1);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDApkText[playerid][7], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDApkText[playerid][7], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDApkText[playerid][7], 0);
	PlayerTextDrawSetProportional(playerid, PhoneTDApkText[playerid][7], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDApkText[playerid][7], 0);

	PhoneTDApkText[playerid][8] = CreatePlayerTextDraw(playerid, 457.000000, 279.000000, "Twitter");
	PlayerTextDrawFont(playerid, PhoneTDApkText[playerid][8], 1);
	PlayerTextDrawLetterSize(playerid, PhoneTDApkText[playerid][8], 0.150000, 0.949998);
	PlayerTextDrawTextSize(playerid, PhoneTDApkText[playerid][8], 400.000000, 107.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDApkText[playerid][8], 0);
	PlayerTextDrawSetShadow(playerid, PhoneTDApkText[playerid][8], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDApkText[playerid][8], 2);
	PlayerTextDrawColor(playerid, PhoneTDApkText[playerid][8], -1);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDApkText[playerid][8], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDApkText[playerid][8], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDApkText[playerid][8], 0);
	PlayerTextDrawSetProportional(playerid, PhoneTDApkText[playerid][8], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDApkText[playerid][8], 0);

	PhoneTDApkText[playerid][9] = CreatePlayerTextDraw(playerid, 457.000000, 327.000000, "Call");
	PlayerTextDrawFont(playerid, PhoneTDApkText[playerid][9], 1);
	PlayerTextDrawLetterSize(playerid, PhoneTDApkText[playerid][9], 0.150000, 0.949998);
	PlayerTextDrawTextSize(playerid, PhoneTDApkText[playerid][9], 400.000000, 107.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDApkText[playerid][9], 0);
	PlayerTextDrawSetShadow(playerid, PhoneTDApkText[playerid][9], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDApkText[playerid][9], 2);
	PlayerTextDrawColor(playerid, PhoneTDApkText[playerid][9], -1);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDApkText[playerid][9], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDApkText[playerid][9], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDApkText[playerid][9], 0);
	PlayerTextDrawSetProportional(playerid, PhoneTDApkText[playerid][9], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDApkText[playerid][9], 0);

	PhoneTDApkText[playerid][10] = CreatePlayerTextDraw(playerid, 422.000000, 327.000000, "Camera");
	PlayerTextDrawFont(playerid, PhoneTDApkText[playerid][10], 1);
	PlayerTextDrawLetterSize(playerid, PhoneTDApkText[playerid][10], 0.150000, 0.949998);
	PlayerTextDrawTextSize(playerid, PhoneTDApkText[playerid][10], 400.000000, 107.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDApkText[playerid][10], 0);
	PlayerTextDrawSetShadow(playerid, PhoneTDApkText[playerid][10], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDApkText[playerid][10], 2);
	PlayerTextDrawColor(playerid, PhoneTDApkText[playerid][10], -1);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDApkText[playerid][10], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDApkText[playerid][10], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDApkText[playerid][10], 0);
	PlayerTextDrawSetProportional(playerid, PhoneTDApkText[playerid][10], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDApkText[playerid][10], 0);

	PhoneTDApkText[playerid][11] = CreatePlayerTextDraw(playerid, 387.000000, 327.000000, "Contacts");
	PlayerTextDrawFont(playerid, PhoneTDApkText[playerid][11], 1);
	PlayerTextDrawLetterSize(playerid, PhoneTDApkText[playerid][11], 0.150000, 0.949998);
	PlayerTextDrawTextSize(playerid, PhoneTDApkText[playerid][11], 400.000000, 107.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDApkText[playerid][11], 0);
	PlayerTextDrawSetShadow(playerid, PhoneTDApkText[playerid][11], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDApkText[playerid][11], 2);
	PlayerTextDrawColor(playerid, PhoneTDApkText[playerid][11], -1);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDApkText[playerid][11], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDApkText[playerid][11], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDApkText[playerid][11], 0);
	PlayerTextDrawSetProportional(playerid, PhoneTDApkText[playerid][11], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDApkText[playerid][11], 0);

	PhoneTDMusicLogo[playerid][0] = CreatePlayerTextDraw(playerid, 374.500000, 174.500000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PhoneTDMusicLogo[playerid][0], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDMusicLogo[playerid][0], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDMusicLogo[playerid][0], 25.000000, 25.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDMusicLogo[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDMusicLogo[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDMusicLogo[playerid][0], 1);
	PlayerTextDrawColor(playerid, PhoneTDMusicLogo[playerid][0], 517431551);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDMusicLogo[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDMusicLogo[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDMusicLogo[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDMusicLogo[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDMusicLogo[playerid][0], 0);

	PhoneTDMusicLogo[playerid][1] = CreatePlayerTextDraw(playerid, 374.500000, 174.500000, "ld_beat:cring");
	PlayerTextDrawFont(playerid, PhoneTDMusicLogo[playerid][1], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDMusicLogo[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDMusicLogo[playerid][1], 25.000000, 25.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDMusicLogo[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDMusicLogo[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDMusicLogo[playerid][1], 1);
	PlayerTextDrawColor(playerid, PhoneTDMusicLogo[playerid][1], 673720575);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDMusicLogo[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDMusicLogo[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDMusicLogo[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDMusicLogo[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDMusicLogo[playerid][1], 0);

	PhoneTDJobLogo[playerid] = CreatePlayerTextDraw(playerid, 415.000000, 179.000000, "HUD:radar_bulldozer");
	PlayerTextDrawFont(playerid, PhoneTDJobLogo[playerid], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDJobLogo[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDJobLogo[playerid], 15.000000, 15.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDJobLogo[playerid], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDJobLogo[playerid], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDJobLogo[playerid], 1);
	PlayerTextDrawColor(playerid, PhoneTDJobLogo[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDJobLogo[playerid], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDJobLogo[playerid], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDJobLogo[playerid], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDJobLogo[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDJobLogo[playerid], 0);

	PhoneTDAdsLogo[playerid][0] = CreatePlayerTextDraw(playerid, 448.500000, 181.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PhoneTDAdsLogo[playerid][0], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDAdsLogo[playerid][0], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDAdsLogo[playerid][0], 15.000000, 10.500000);
	PlayerTextDrawSetOutline(playerid, PhoneTDAdsLogo[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDAdsLogo[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDAdsLogo[playerid][0], 1);
	PlayerTextDrawColor(playerid, PhoneTDAdsLogo[playerid][0], -1);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDAdsLogo[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDAdsLogo[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDAdsLogo[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDAdsLogo[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDAdsLogo[playerid][0], 0);

	PhoneTDAdsLogo[playerid][1] = CreatePlayerTextDraw(playerid, 449.500000, 182.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PhoneTDAdsLogo[playerid][1], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDAdsLogo[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDAdsLogo[playerid][1], 13.000000, 1.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDAdsLogo[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDAdsLogo[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDAdsLogo[playerid][1], 1);
	PlayerTextDrawColor(playerid, PhoneTDAdsLogo[playerid][1], 255);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDAdsLogo[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDAdsLogo[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDAdsLogo[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDAdsLogo[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDAdsLogo[playerid][1], 0);

	PhoneTDAdsLogo[playerid][2] = CreatePlayerTextDraw(playerid, 449.500000, 184.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PhoneTDAdsLogo[playerid][2], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDAdsLogo[playerid][2], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDAdsLogo[playerid][2], 10.000000, 1.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDAdsLogo[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDAdsLogo[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDAdsLogo[playerid][2], 1);
	PlayerTextDrawColor(playerid, PhoneTDAdsLogo[playerid][2], 255);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDAdsLogo[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDAdsLogo[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDAdsLogo[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDAdsLogo[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDAdsLogo[playerid][2], 0);

	PhoneTDAdsLogo[playerid][3] = CreatePlayerTextDraw(playerid, 449.500000, 186.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PhoneTDAdsLogo[playerid][3], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDAdsLogo[playerid][3], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDAdsLogo[playerid][3], 12.500000, 1.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDAdsLogo[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDAdsLogo[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDAdsLogo[playerid][3], 1);
	PlayerTextDrawColor(playerid, PhoneTDAdsLogo[playerid][3], 255);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDAdsLogo[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDAdsLogo[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDAdsLogo[playerid][3], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDAdsLogo[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDAdsLogo[playerid][3], 0);

	PhoneTDAdsLogo[playerid][4] = CreatePlayerTextDraw(playerid, 449.500000, 188.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PhoneTDAdsLogo[playerid][4], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDAdsLogo[playerid][4], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDAdsLogo[playerid][4], 8.500000, 1.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDAdsLogo[playerid][4], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDAdsLogo[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDAdsLogo[playerid][4], 1);
	PlayerTextDrawColor(playerid, PhoneTDAdsLogo[playerid][4], 255);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDAdsLogo[playerid][4], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDAdsLogo[playerid][4], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDAdsLogo[playerid][4], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDAdsLogo[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDAdsLogo[playerid][4], 0);

	PhoneTDAdsLogo[playerid][5] = CreatePlayerTextDraw(playerid, 449.500000, 190.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PhoneTDAdsLogo[playerid][5], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDAdsLogo[playerid][5], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDAdsLogo[playerid][5], 12.000000, 1.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDAdsLogo[playerid][5], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDAdsLogo[playerid][5], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDAdsLogo[playerid][5], 1);
	PlayerTextDrawColor(playerid, PhoneTDAdsLogo[playerid][5], 255);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDAdsLogo[playerid][5], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDAdsLogo[playerid][5], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDAdsLogo[playerid][5], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDAdsLogo[playerid][5], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDAdsLogo[playerid][5], 0);

	PhoneTDBankLogo[playerid] = CreatePlayerTextDraw(playerid, 380.000000, 219.000000, "HUD:radar_cash");
	PlayerTextDrawFont(playerid, PhoneTDBankLogo[playerid], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDBankLogo[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDBankLogo[playerid], 15.000000, 15.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDBankLogo[playerid], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDBankLogo[playerid], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDBankLogo[playerid], 1);
	PlayerTextDrawColor(playerid, PhoneTDBankLogo[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDBankLogo[playerid], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDBankLogo[playerid], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDBankLogo[playerid], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDBankLogo[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDBankLogo[playerid], 0);

	PhoneTDTaxiLogo[playerid][0] = CreatePlayerTextDraw(playerid, 409.500000, 214.500000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PhoneTDTaxiLogo[playerid][0], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDTaxiLogo[playerid][0], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDTaxiLogo[playerid][0], 25.000000, 25.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDTaxiLogo[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDTaxiLogo[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDTaxiLogo[playerid][0], 1);
	PlayerTextDrawColor(playerid, PhoneTDTaxiLogo[playerid][0], -2686721);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDTaxiLogo[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDTaxiLogo[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDTaxiLogo[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDTaxiLogo[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDTaxiLogo[playerid][0], 0);

	PhoneTDTaxiLogo[playerid][1] = CreatePlayerTextDraw(playerid, 412.000000, 217.250000, "ld_beat:cring");
	PlayerTextDrawFont(playerid, PhoneTDTaxiLogo[playerid][1], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDTaxiLogo[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDTaxiLogo[playerid][1], 20.000000, 20.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDTaxiLogo[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDTaxiLogo[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDTaxiLogo[playerid][1], 1);
	PlayerTextDrawColor(playerid, PhoneTDTaxiLogo[playerid][1], 255);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDTaxiLogo[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDTaxiLogo[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDTaxiLogo[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDTaxiLogo[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDTaxiLogo[playerid][1], 0);

	PhoneTDAirDropLogo[playerid] = CreatePlayerTextDraw(playerid, 449.500000, 219.000000, "HUD:radar_centre");
	PlayerTextDrawFont(playerid, PhoneTDAirDropLogo[playerid], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDAirDropLogo[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDAirDropLogo[playerid], 15.000000, 15.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDAirDropLogo[playerid], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDAirDropLogo[playerid], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDAirDropLogo[playerid], 1);
	PlayerTextDrawColor(playerid, PhoneTDAirDropLogo[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDAirDropLogo[playerid], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDAirDropLogo[playerid], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDAirDropLogo[playerid], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDAirDropLogo[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDAirDropLogo[playerid], 0);

	PhoneTDSettingsLogo[playerid] = CreatePlayerTextDraw(playerid, 379.500000, 259.000000, "HUD:radar_runway");
	PlayerTextDrawFont(playerid, PhoneTDSettingsLogo[playerid], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDSettingsLogo[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDSettingsLogo[playerid], 15.000000, 15.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDSettingsLogo[playerid], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDSettingsLogo[playerid], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDSettingsLogo[playerid], 1);
	PlayerTextDrawColor(playerid, PhoneTDSettingsLogo[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDSettingsLogo[playerid], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDSettingsLogo[playerid], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDSettingsLogo[playerid], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDSettingsLogo[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDSettingsLogo[playerid], 0);

	PhoneTDMapsLogo[playerid][0] = CreatePlayerTextDraw(playerid, 409.500000, 254.500000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PhoneTDMapsLogo[playerid][0], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDMapsLogo[playerid][0], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDMapsLogo[playerid][0], 25.000000, 25.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDMapsLogo[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDMapsLogo[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDMapsLogo[playerid][0], 1);
	PlayerTextDrawColor(playerid, PhoneTDMapsLogo[playerid][0], 852308735);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDMapsLogo[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDMapsLogo[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDMapsLogo[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDMapsLogo[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDMapsLogo[playerid][0], 0);

	PhoneTDMapsLogo[playerid][1] = CreatePlayerTextDraw(playerid, 414.000000, 268.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PhoneTDMapsLogo[playerid][1], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDMapsLogo[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDMapsLogo[playerid][1], 16.000000, 6.500000);
	PlayerTextDrawSetOutline(playerid, PhoneTDMapsLogo[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDMapsLogo[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDMapsLogo[playerid][1], 1);
	PlayerTextDrawColor(playerid, PhoneTDMapsLogo[playerid][1], -1);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDMapsLogo[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDMapsLogo[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDMapsLogo[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDMapsLogo[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDMapsLogo[playerid][1], 0);

	PhoneTDMapsLogo[playerid][2] = CreatePlayerTextDraw(playerid, 422.250000, 260.000000, "!");
	PlayerTextDrawFont(playerid, PhoneTDMapsLogo[playerid][2], 2);
	PlayerTextDrawLetterSize(playerid, PhoneTDMapsLogo[playerid][2], 0.300000, 1.500000);
	PlayerTextDrawTextSize(playerid, PhoneTDMapsLogo[playerid][2], 400.000000, 107.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDMapsLogo[playerid][2], 0);
	PlayerTextDrawSetShadow(playerid, PhoneTDMapsLogo[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDMapsLogo[playerid][2], 2);
	PlayerTextDrawColor(playerid, PhoneTDMapsLogo[playerid][2], -16776961);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDMapsLogo[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDMapsLogo[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDMapsLogo[playerid][2], 0);
	PlayerTextDrawSetProportional(playerid, PhoneTDMapsLogo[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDMapsLogo[playerid][2], 0);

	PhoneTDXLogo[playerid][0] = CreatePlayerTextDraw(playerid, 444.500000, 254.500000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PhoneTDXLogo[playerid][0], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDXLogo[playerid][0], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDXLogo[playerid][0], 25.000000, 25.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDXLogo[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDXLogo[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDXLogo[playerid][0], 1);
	PlayerTextDrawColor(playerid, PhoneTDXLogo[playerid][0], 255);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDXLogo[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDXLogo[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDXLogo[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDXLogo[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDXLogo[playerid][0], 0);

	PhoneTDXLogo[playerid][1] = CreatePlayerTextDraw(playerid, 457.250000, 259.000000, "X");
	PlayerTextDrawFont(playerid, PhoneTDXLogo[playerid][1], 2);
	PlayerTextDrawLetterSize(playerid, PhoneTDXLogo[playerid][1], 0.300000, 1.500000);
	PlayerTextDrawTextSize(playerid, PhoneTDXLogo[playerid][1], 400.000000, 107.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDXLogo[playerid][1], 0);
	PlayerTextDrawSetShadow(playerid, PhoneTDXLogo[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDXLogo[playerid][1], 2);
	PlayerTextDrawColor(playerid, PhoneTDXLogo[playerid][1], -1);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDXLogo[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDXLogo[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDXLogo[playerid][1], 0);
	PlayerTextDrawSetProportional(playerid, PhoneTDXLogo[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDXLogo[playerid][1], 0);

	PhoneTDContactsLogo[playerid] = CreatePlayerTextDraw(playerid, 379.500000, 307.000000, "HUD:radar_saveGame");
	PlayerTextDrawFont(playerid, PhoneTDContactsLogo[playerid], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDContactsLogo[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDContactsLogo[playerid], 15.000000, 15.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDContactsLogo[playerid], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDContactsLogo[playerid], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDContactsLogo[playerid], 1);
	PlayerTextDrawColor(playerid, PhoneTDContactsLogo[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDContactsLogo[playerid], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDContactsLogo[playerid], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDContactsLogo[playerid], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDContactsLogo[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDContactsLogo[playerid], 0);

	PhoneTDCamLogo[playerid][0] = CreatePlayerTextDraw(playerid, 414.500000, 309.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PhoneTDCamLogo[playerid][0], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDCamLogo[playerid][0], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDCamLogo[playerid][0], 15.000000, 10.500000);
	PlayerTextDrawSetOutline(playerid, PhoneTDCamLogo[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDCamLogo[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDCamLogo[playerid][0], 1);
	PlayerTextDrawColor(playerid, PhoneTDCamLogo[playerid][0], 673720575);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDCamLogo[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDCamLogo[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDCamLogo[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDCamLogo[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDCamLogo[playerid][0], 0);

	PhoneTDCamLogo[playerid][1] = CreatePlayerTextDraw(playerid, 417.000000, 309.500000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PhoneTDCamLogo[playerid][1], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDCamLogo[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDCamLogo[playerid][1], 10.000000, 10.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDCamLogo[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDCamLogo[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDCamLogo[playerid][1], 1);
	PlayerTextDrawColor(playerid, PhoneTDCamLogo[playerid][1], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDCamLogo[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDCamLogo[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDCamLogo[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDCamLogo[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDCamLogo[playerid][1], 0);

	PhoneTDCamLogo[playerid][2] = CreatePlayerTextDraw(playerid, 426.000000, 309.500000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PhoneTDCamLogo[playerid][2], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDCamLogo[playerid][2], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDCamLogo[playerid][2], 3.000000, 3.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDCamLogo[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDCamLogo[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDCamLogo[playerid][2], 1);
	PlayerTextDrawColor(playerid, PhoneTDCamLogo[playerid][2], -1);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDCamLogo[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDCamLogo[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDCamLogo[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDCamLogo[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDCamLogo[playerid][2], 0);

	PhoneTDCallLogo[playerid] = CreatePlayerTextDraw(playerid, 450.500000, 307.000000, "ld_chat:badchat");
	PlayerTextDrawFont(playerid, PhoneTDCallLogo[playerid], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTDCallLogo[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTDCallLogo[playerid], 15.000000, 15.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTDCallLogo[playerid], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTDCallLogo[playerid], 0);
	PlayerTextDrawAlignment(playerid, PhoneTDCallLogo[playerid], 1);
	PlayerTextDrawColor(playerid, PhoneTDCallLogo[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, PhoneTDCallLogo[playerid], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTDCallLogo[playerid], 50);
	PlayerTextDrawUseBox(playerid, PhoneTDCallLogo[playerid], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTDCallLogo[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTDCallLogo[playerid], 0);

    // Call screen
    PhoneTD_CallCloseButton[playerid] = CreatePlayerTextDraw(playerid, 404.000000, 305.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PhoneTD_CallCloseButton[playerid], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTD_CallCloseButton[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTD_CallCloseButton[playerid], 35.000000, 35.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTD_CallCloseButton[playerid], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTD_CallCloseButton[playerid], 0);
	PlayerTextDrawAlignment(playerid, PhoneTD_CallCloseButton[playerid], 1);
	PlayerTextDrawColor(playerid, PhoneTD_CallCloseButton[playerid], -703524353);
	PlayerTextDrawBackgroundColor(playerid, PhoneTD_CallCloseButton[playerid], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTD_CallCloseButton[playerid], 50);
	PlayerTextDrawUseBox(playerid, PhoneTD_CallCloseButton[playerid], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTD_CallCloseButton[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTD_CallCloseButton[playerid], 1);

	PhoneTD_CallCloseIcon[playerid] = CreatePlayerTextDraw(playerid, 422.000000, 319.000000, "U");
	PlayerTextDrawFont(playerid, PhoneTD_CallCloseIcon[playerid], 1);
	PlayerTextDrawLetterSize(playerid, PhoneTD_CallCloseIcon[playerid], 0.908333, 0.800000);
	PlayerTextDrawTextSize(playerid, PhoneTD_CallCloseIcon[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTD_CallCloseIcon[playerid], 0);
	PlayerTextDrawSetShadow(playerid, PhoneTD_CallCloseIcon[playerid], 0);
	PlayerTextDrawAlignment(playerid, PhoneTD_CallCloseIcon[playerid], 2);
	PlayerTextDrawColor(playerid, PhoneTD_CallCloseIcon[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, PhoneTD_CallCloseIcon[playerid], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTD_CallCloseIcon[playerid], 50);
	PlayerTextDrawUseBox(playerid, PhoneTD_CallCloseIcon[playerid], 0);
	PlayerTextDrawSetProportional(playerid, PhoneTD_CallCloseIcon[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTD_CallCloseIcon[playerid], 0);

	PhoneTD_CallName[playerid] = CreatePlayerTextDraw(playerid, 422.000000, 168.000000, "Andrey Voznesenskiy");
	PlayerTextDrawFont(playerid, PhoneTD_CallName[playerid], 1);
	PlayerTextDrawLetterSize(playerid, PhoneTD_CallName[playerid], 0.215000, 1.200000);
	PlayerTextDrawTextSize(playerid, PhoneTD_CallName[playerid], 400.000000, 242.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTD_CallName[playerid], 0);
	PlayerTextDrawSetShadow(playerid, PhoneTD_CallName[playerid], 0);
	PlayerTextDrawAlignment(playerid, PhoneTD_CallName[playerid], 2);
	PlayerTextDrawColor(playerid, PhoneTD_CallName[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, PhoneTD_CallName[playerid], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTD_CallName[playerid], 50);
	PlayerTextDrawUseBox(playerid, PhoneTD_CallName[playerid], 0);
	PlayerTextDrawSetProportional(playerid, PhoneTD_CallName[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTD_CallName[playerid], 0);

	PhoneTD_CallStatus[playerid] = CreatePlayerTextDraw(playerid, 422.000000, 182.000000, "00.00.00");
	PlayerTextDrawFont(playerid, PhoneTD_CallStatus[playerid], 1);
	PlayerTextDrawLetterSize(playerid, PhoneTD_CallStatus[playerid], 0.150000, 0.899999);
	PlayerTextDrawTextSize(playerid, PhoneTD_CallStatus[playerid], 400.000000, 242.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTD_CallStatus[playerid], 0);
	PlayerTextDrawSetShadow(playerid, PhoneTD_CallStatus[playerid], 0);
	PlayerTextDrawAlignment(playerid, PhoneTD_CallStatus[playerid], 2);
	PlayerTextDrawColor(playerid, PhoneTD_CallStatus[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, PhoneTD_CallStatus[playerid], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTD_CallStatus[playerid], 50);
	PlayerTextDrawUseBox(playerid, PhoneTD_CallStatus[playerid], 0);
	PlayerTextDrawSetProportional(playerid, PhoneTD_CallStatus[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTD_CallStatus[playerid], 0);



	PhoneTD_CallRejectButton[playerid] = CreatePlayerTextDraw(playerid, 430.000000, 305.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PhoneTD_CallRejectButton[playerid], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTD_CallRejectButton[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTD_CallRejectButton[playerid], 35.000000, 35.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTD_CallRejectButton[playerid], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTD_CallRejectButton[playerid], 0);
	PlayerTextDrawAlignment(playerid, PhoneTD_CallRejectButton[playerid], 1);
	PlayerTextDrawColor(playerid, PhoneTD_CallRejectButton[playerid], -703524353);
	PlayerTextDrawBackgroundColor(playerid, PhoneTD_CallRejectButton[playerid], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTD_CallRejectButton[playerid], 50);
	PlayerTextDrawUseBox(playerid, PhoneTD_CallRejectButton[playerid], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTD_CallRejectButton[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTD_CallRejectButton[playerid], 1);

	PhoneTD_CallRejectIcon[playerid] = CreatePlayerTextDraw(playerid, 448.000000, 319.000000, "U");
	PlayerTextDrawFont(playerid, PhoneTD_CallRejectIcon[playerid], 1);
	PlayerTextDrawLetterSize(playerid, PhoneTD_CallRejectIcon[playerid], 0.908333, 0.800000);
	PlayerTextDrawTextSize(playerid, PhoneTD_CallRejectIcon[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTD_CallRejectIcon[playerid], 0);
	PlayerTextDrawSetShadow(playerid, PhoneTD_CallRejectIcon[playerid], 0);
	PlayerTextDrawAlignment(playerid, PhoneTD_CallRejectIcon[playerid], 2);
	PlayerTextDrawColor(playerid, PhoneTD_CallRejectIcon[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, PhoneTD_CallRejectIcon[playerid], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTD_CallRejectIcon[playerid], 50);
	PlayerTextDrawUseBox(playerid, PhoneTD_CallRejectIcon[playerid], 0);
	PlayerTextDrawSetProportional(playerid, PhoneTD_CallRejectIcon[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTD_CallRejectIcon[playerid], 0);

	PhoneTD_CallPickupButton[playerid] = CreatePlayerTextDraw(playerid, 379.000000, 305.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PhoneTD_CallPickupButton[playerid], 4);
	PlayerTextDrawLetterSize(playerid, PhoneTD_CallPickupButton[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PhoneTD_CallPickupButton[playerid], 35.000000, 35.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTD_CallPickupButton[playerid], 1);
	PlayerTextDrawSetShadow(playerid, PhoneTD_CallPickupButton[playerid], 0);
	PlayerTextDrawAlignment(playerid, PhoneTD_CallPickupButton[playerid], 1);
	PlayerTextDrawColor(playerid, PhoneTD_CallPickupButton[playerid], 1556351231);
	PlayerTextDrawBackgroundColor(playerid, PhoneTD_CallPickupButton[playerid], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTD_CallPickupButton[playerid], 50);
	PlayerTextDrawUseBox(playerid, PhoneTD_CallPickupButton[playerid], 1);
	PlayerTextDrawSetProportional(playerid, PhoneTD_CallPickupButton[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTD_CallPickupButton[playerid], 1);

	PhoneTD_CallPickupIcon[playerid] = CreatePlayerTextDraw(playerid, 397.000000, 319.000000, "U");
	PlayerTextDrawFont(playerid, PhoneTD_CallPickupIcon[playerid], 1);
	PlayerTextDrawLetterSize(playerid, PhoneTD_CallPickupIcon[playerid], 0.908333, 0.800000);
	PlayerTextDrawTextSize(playerid, PhoneTD_CallPickupIcon[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PhoneTD_CallPickupIcon[playerid], 0);
	PlayerTextDrawSetShadow(playerid, PhoneTD_CallPickupIcon[playerid], 0);
	PlayerTextDrawAlignment(playerid, PhoneTD_CallPickupIcon[playerid], 2);
	PlayerTextDrawColor(playerid, PhoneTD_CallPickupIcon[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, PhoneTD_CallPickupIcon[playerid], 255);
	PlayerTextDrawBoxColor(playerid, PhoneTD_CallPickupIcon[playerid], 50);
	PlayerTextDrawUseBox(playerid, PhoneTD_CallPickupIcon[playerid], 0);
	PlayerTextDrawSetProportional(playerid, PhoneTD_CallPickupIcon[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, PhoneTD_CallPickupIcon[playerid], 0);
}